/* Spanish: generated by tools/translate.mjs from the English pack (gemini-3.8-flash). Edit freely. */
"use strict";
DF.L = DF.L || {};
DF.L.es = {
  "brand": {
    "tagline": "Sobrevive al DevFest",
    "sub": "El juego cooperativo para quien organiza eventos tech",
    "by": "{chapter} presenta",
    "byAny": "Tu comunidad presenta",
    "disclaimer": "Proyecto de la comunidad, no es un producto oficial de Google."
  },
  "ui": {
    "title": {
      "play": "Jugar la temporada",
      "playSub": "6 eventos, de meetup a DevFest",
      "quick": "Partida rápida",
      "quickSub": "Elige un evento y listo",
      "forge": "La crisis de tu chapter",
      "forgeSub": "Convierte un problema real en carta",
      "help": "Cómo jugar",
      "about": "El proyecto",
      "record": "Récord: {fb}/5 · {score} puntos",
      "noRecord": "Ningún evento organizado. Aún.",
      "aiOn": "Gemini activo",
      "aiOff": "Contenido offline",
      "marquee": [
        "FALTA EL SPEAKER",
        "CAÍDA DE WI-FI",
        "SIN CAFÉ",
        "SALA LLENA",
        "MURPHY ESTÁ AQUÍ",
        "PIZZA PERDIDA",
        "IMPRESORA ATASCADA",
        "EL SPONSOR TE BUSCA",
        "212 RSVPS, 168 ASIENTOS"
      ],
      "notif": [
        "El speaker pide un adaptador USB-C",
        "Tienes 47 mensajes sin leer",
        "El catering pregunta cuántas pizzas",
        "¿Alguien ha visto las llaves del aula?",
        "El sponsor quiere el logo más grande",
        "Mamá: ¿has comido?"
      ]
    },
    "season": {
      "title": "La temporada",
      "sub": "Tres objetivos por evento: una estrella desbloquea el siguiente.",
      "locked": "Primero: {prev}",
      "play": "Jugar",
      "best": "Mejor: {fb}/5",
      "rounds": "{n} rondas de preparación",
      "people": "~{n} personas",
      "minutes": "{n} min"
    },
    "setup": {
      "eyebrow": "Nuevo evento",
      "title": "¿Quién organiza?",
      "venue": "Sede",
      "relax": "Modo relax",
      "relaxSub": "más tiempo para cada marrón y para el chat.",
      "soldout": "Sold-out",
      "soldoutSub": "+40% de gente, más líos, una hora punta más. Récord aparte.",
      "soldoutLocked": "Sold-out: se desbloquea con 3 estrellas en este evento.",
      "modes": {
        "solo": [
          "En solitario",
          "Llevas el lead. Puedes fichar a un co-organizer."
        ],
        "duo": [
          "Dos jugadores",
          "Un teclado: WASD+Space y flechas+Enter."
        ],
        "online": [
          "Online",
          "Sala con código, hasta 4 leads."
        ]
      },
      "onlineLocal": "Sin servidor: sala entre pestañas de este navegador.",
      "chapter": "Comunidad o chapter",
      "chapterPh": "ej. GDG London",
      "city": "Ciudad",
      "cityPh": "Tu ciudad",
      "player": "Jugador {n}",
      "role": "Rol",
      "name": "Nombre",
      "back": "Atrás",
      "start": "Empezar a preparar",
      "startDay": "Abrir puertas",
      "code": "Código de sala",
      "join": "Entrar",
      "create": "Crear sala",
      "codeLen": "El código tiene 4 caracteres.",
      "notFound": "Sala {code} no encontrada.",
      "noRooms": "Este navegador no soporta salas online."
    },
    "lobby": {
      "recaptcha": "Salas online protegidas de bots por Google reCAPTCHA.",
      "terms": "Términos",
      "eyebrow": "Sala online · {via}",
      "code": "Código",
      "host": "Pasa el código a los otros leads. Máximo cuatro.",
      "guest": "Estás dentro: el host inicia la preparación.",
      "you": "tú",
      "other": "listo",
      "leave": "Salir",
      "copy": "Copiar código",
      "copied": "Copiado",
      "start": "Empezar",
      "gone": "El host ha cerrado la sala."
    },
    "prep": {
      "title": "La cuenta atrás",
      "hint": "Cada punto es una tarde libre. Lo que nadie asuma pasará de todas formas.",
      "hintTeam": "Elige quién se encarga y luego la opción.",
      "hintOnline": "Cada uno gasta sus puntos: habladlo.",
      "close": "Cerrar ronda",
      "next": "Siguiente",
      "toDay": "El día de antes →",
      "ready": "Estoy listo",
      "isReady": "Listo ✓",
      "hostNext": "El anfitrión pasa a la siguiente ronda.",
      "ignore": "Si nadie se encarga",
      "why": "¿Por qué?",
      "free": "gratis",
      "who": "✓ {name}",
      "tired": "{name} no da para más esta ronda.",
      "discount": "−1 para {role}",
      "ai": "✨ De tu zona",
      "aiLoading": "Gemini está redactando una carta para {city}…",
      "aiLoadingAny": "Gemini está redactando una carta a medida…",
      "results": "Cómo fue",
      "done": "HECHO",
      "skipped": "SALTADO",
      "overtime": "Horas extra: {n} tardes más, −{e} de energía.",
      "rounds": {
        "1": [
          "−1 semana"
        ],
        "2": [
          "−3 semanas",
          "−1 semana"
        ],
        "4": [
          "−12 semanas",
          "−8 semanas",
          "−4 semanas",
          "−1 semana"
        ]
      }
    },
    "ai": {
      "safeTitle": "Tu clave se queda en tu navegador.",
      "safeText": "Nunca pasa por nuestros servidores ni la guardamos: va directo de ti a Google. Puedes borrarla cuando quieras.",
      "stays": "Se queda en este navegador y solo va a Google.",
      "statusCap": "Pausado hasta mañana: se agotaron las 150 peticiones de hoy (protege tu cuota).",
      "title": "Gemini en el juego",
      "chipOff": "Activar Gemini",
      "chipNA": "IA no disponible",
      "intro": "Overbooked! funciona genial sin IA. Con tu clave de Gemini añade contenido creado para tu chapter:",
      "feats": [
        "una carta «de tu zona» en cada ronda de Countdown",
        "el chat del staff adaptado a tu ciudad",
        "la Gaceta local y el consejo del coach en la retro",
        "la forja: de una anécdota real a una carta"
      ],
      "statusOff": "IA desactivada",
      "statusPaused": "Pausada por ti",
      "statusKey": "Activa con tu clave · {model}",
      "statusServer": "Activa: cortesía del anfitrión de la partida · {model}",
      "unavailableShort": "No disponible en esta versión",
      "enable": "Reactivar",
      "disable": "Desactivar la IA",
      "yourKey": "Tu clave de Gemini",
      "saved": "Clave guardada {key} · {where}",
      "whereDevice": "en este dispositivo",
      "whereSession": "solo para esta sesión",
      "remove": "Eliminar la clave",
      "keyLabel": "Clave de API de Gemini",
      "test": "Probar y activar",
      "testing": "Comprobando la clave con Google…",
      "ok": "¡Listo! Gemini activado con {model}.",
      "remember": "Recordarla en este dispositivo",
      "rememberSub": "si no, desaparecerá al cerrar la pestaña.",
      "err": {
        "format": "No parece una clave de Gemini válida.",
        "rejected": "Google rechazó la clave: comprueba que esté activa y que este sitio esté autorizado.",
        "quota": "La clave agotó su cuota por ahora: inténtalo más tarde.",
        "models": "La clave funciona, pero no tiene acceso a los modelos Gemini Flash.",
        "network": "Google no responde: revisa tu conexión e inténtalo de nuevo.",
        "http": "Algo salió mal: inténtalo de nuevo."
      },
      "howTitle": "Cómo conseguir una de forma segura (2 minutos)",
      "how": [
        "Crea una clave exclusiva para el juego en Google AI Studio.",
        "En la consola de Google Cloud limítala: solo «Generative Language API» y solo este sitio como referrer.",
        "Configura un presupuesto bajo en el proyecto: en Europa las apps usan el plan de pago, y una partida cuesta unos céntimos."
      ],
      "linkStudio": "Google AI Studio",
      "linkConsole": "Credenciales de Google Cloud",
      "linkBilling": "Facturación de Gemini",
      "privacy": "La clave se queda en tu navegador y solo va a Google: nunca pasa por nuestros servidores ni la almacenamos. Con la IA activa, Gemini recibe el nombre del chapter, la ciudad, las estadísticas de la jornada y las anécdotas que escribas en la forja.",
      "unavailable": "La IA no está disponible en esta versión: la página no puede conectar con Google. Juega desde la web oficial para usar tu clave."
    },
    "acct": {
      "eyebrow": "Cuenta",
      "chip": "Iniciar sesión",
      "title": "Iniciar sesión es opcional",
      "freeTitle": "Puedes jugar sin cuenta",
      "freeText": "Tus estrellas, kit y cartas se quedan en este dispositivo igualmente. Una cuenta solo sirve para llevarlos a otros dispositivos y poner a tu chapter en la clasificación.",
      "feats": [
        "Encuentra tus estrellas, kit y cartas forjadas en el móvil y en el portátil.",
        "Pon a tu chapter en la clasificación de la temporada.",
        "Cero newsletters, a menos que tú la pidas."
      ],
      "signIn": "Iniciar sesión con Google",
      "loading": "Preparando inicio de sesión…",
      "privacyNote": "Solo guardamos lo necesario para sincronizar, y puedes borrarlo todo cuando quieras.",
      "unavailable": "El inicio de sesión solo funciona en la web del juego. Aquí, las estrellas y cartas se quedan en este navegador.",
      "hello": "¡Hola, {name}!",
      "as": "Sesión iniciada como {email}. Solo tú puedes verlo.",
      "signOut": "Cerrar sesión",
      "syncing": "Sincronizando…",
      "synced": "Progreso guardado a las {time}",
      "syncErr": "No se puede guardar online ahora mismo: lo reintentaré con el próximo cambio.",
      "boardTitle": "Tu chapter en la clasificación",
      "boardOn": "Poner a mi chapter en la clasificación",
      "boardOnSub": "Cuentan tus estrellas de la temporada ({n} ⭐). La clasificación muestra el nombre del chapter, nunca el tuyo.",
      "boardLive": "{chapter} está en la clasificación: se actualiza cada pocos minutos.",
      "boardPending": "Los nombres que empiezan por GDG, GDSC o WTM aparecen al instante; los demás, tras revisarlos.",
      "boardNoName": "Escribe el nombre de tu chapter (de 2 a 40 caracteres).",
      "contactTitle": "Contacto",
      "consent": "Podéis enviarme emails sobre novedades del juego.",
      "consentSub": "Opcional. Usamos tu email solo para OVERBOOKED! y solo con esta casilla marcada. Desmárcala cuando quieras.",
      "deleteTitle": "Eliminar cuenta",
      "deleteText": "Elimina la cuenta y todo lo guardado online. La partida en este dispositivo se queda como está.",
      "delete": "Eliminar cuenta",
      "deleteSure": "¿Seguro? La cuenta y tus datos online desaparecerán para siempre, clasificación incluida.",
      "deleteYes": "Sí, eliminar",
      "deleteNo": "Cancelar",
      "reauth": "Por seguridad, Google pide confirmar que eres tú. Luego, la cuenta se borrará.",
      "reauthBtn": "Confirmar con Google y eliminar",
      "deleted": "Cuenta eliminada. Tus datos online han desaparecido.",
      "err": {
        "popup": "Tu navegador bloqueó la ventana de Google: inténtalo de nuevo o permite las ventanas emergentes aquí.",
        "disabled": "El inicio de sesión con Google aún no está activado. Vuelve a intentarlo pronto.",
        "domain": "El inicio de sesión no funciona desde esta dirección.",
        "network": "Error de red: inténtalo de nuevo.",
        "check": "Falló la comprobación antibot: recarga la página y prueba otra vez.",
        "denied": "No permitido.",
        "load": "No se puede cargar el inicio de sesión: comprueba tu conexión.",
        "generic": "Algo salió mal: inténtalo de nuevo."
      }
    },
    "board": {
      "short": "Clasificación",
      "eyebrow": "La temporada de los chapters",
      "title": "Clasificación de chapters",
      "intro": "Estrellas de temporada de los jugadores, sumadas por chapter. Cada uno aporta hasta 18 estrellas: para subir, trae a más gente de tu equipo.",
      "loading": "Cargando la clasificación…",
      "empty": "Aún no hay chapters: el primer puesto está libre.",
      "error": "No se puede cargar la clasificación: prueba más tarde.",
      "unavailable": "La clasificación solo está disponible en la web del juego.",
      "meta": "{chapters} chapters · {players} jugadores · se actualiza cada pocos minutos",
      "join": "Suma a tu chapter",
      "mine": "Mi chapter"
    },
    "privacy": {
      "link": "Privacidad",
      "eyebrow": "Privacidad",
      "title": "Privacidad, en claro",
      "intro": "Sin cookies, sin anuncios y sin rastreo entre sitios. Esto es lo que llega a nuestros servidores y por qué.",
      "statsTitle": "Estadísticas anónimas",
      "statsText": "Para saber si el juego ayuda a las comunidades, contamos visitas y días jugados. Cada recuento lleva pocos datos: idioma, de dónde vienes (LinkedIn, Medium…), móvil u ordenador, zona horaria, evento, estrellas, IA activada o no, y el nombre del chapter si empieza por GDG, GDSC o WTM. Ni IPs ni identificadores: el servidor solo suma 1 a los totales.",
      "playTitle": "Diario de partidas",
      "playText": "Para mejorar el juego guardamos un resumen anónimo de cada día: objetivos, problemas que se pasaron, respuestas del chat, elecciones del Countdown, tiempo de juego, si lo dejas a medias y errores técnicos. Solo la fecha, ningún identificador y jamás para marketing. Se borran solos tras 12 meses.",
      "logsTitle": "Registros técnicos",
      "logsText": "Como cualquier web, los registros de Google Cloud guardan la IP, el navegador y la página de cada petición durante 30 días. Solo se usan para seguridad y resolución de errores, nunca para contar o perfilar a los jugadores.",
      "statsOn": "Colaborar con estadísticas anónimas",
      "statsOnSub": "Incluye el diario de partidas. Desactívalo cuando quieras: el juego funciona igual.",
      "statsDnt": "Tu navegador pide no ser rastreado: no enviamos estadísticas.",
      "statsOff": "Las estadísticas están desactivadas en esta versión del juego.",
      "acctTitle": "Cuenta de Google (opcional)",
      "acctText": "Si inicias sesión con Google, guardamos tu ID, nombre y correo (gestionados por Firebase Authentication), estrellas, kit, cartas forjadas y nombre del chapter. Sirven para sincronizar tus dispositivos y, si quieres, para la clasificación (donde solo se ve el chapter). Solo te escribiremos si das tu permiso. Todo se conserva hasta que borres la cuenta en la pantalla Cuenta.",
      "roomsTitle": "Salas online",
      "roomsText": "Las salas usan un inicio de sesión anónimo temporal y Google reCAPTCHA para frenar bots. Los datos de la partida desaparecen cuando el host cierra la sala; los accesos anónimos se borran solos a los 30 días.",
      "aiTitle": "Gemini",
      "aiText": "Si activas la IA, tu clave se queda en tu navegador y viaja solo a Google: nunca pasa por nuestros servidores.",
      "whoTitle": "Quiénes somos y quién nos ayuda",
      "whoText": "OVERBOOKED! es un proyecto de comunidad creado por Nicola Guglielmi (GDE). El juego usa Google Firebase (Hosting, Authentication, Cloud Functions y Realtime Database, con datos de juego y recuentos en Bélgica) y fuentes de Google Fonts.",
      "contact": "Preguntas o solicitudes sobre tus datos:",
      "updated": "Última actualización: {date}"
    },
    "coach": {
      "ok": "Entendido",
      "next": "Siguiente",
      "done": "Hecho",
      "off": "No más consejos",
      "more": "+{n}",
      "again": "Ver consejos de nuevo",
      "reset": "Consejos reactivados"
    },
    "goals": {
      "rating": "Valoración de al menos {min}",
      "onTime": "Todas las charlas a tiempo",
      "noCancel": "Ninguna charla cancelada",
      "pizza": "La pizza llega caliente",
      "lab": "El Lab no se atasca",
      "chat": "Responde a {n} mensajes",
      "care": "Que nadie se quede atrás",
      "coc": "Todos los reportes gestionados",
      "stream": "El stream no se corta",
      "vip": "Recibe al VIP",
      "mentors": "Desbloquea {n} equipos",
      "demo": "Todas las demos en pantalla",
      "murphy": "Frena a Murphy"
    },
    "weekly": {
      "stub": "Reto semanal",
      "stubSub": "{event}: el mismo día para todos",
      "eyebrow": "Reto semanal · {week}",
      "rules": "Hasta el domingo, el mismo día para todos: mismos marrones, mismas horas punta, preparación estándar, sin kit ni modo relax. Elige rol y juega las veces que quieras: cuenta tu mejor puntuación.",
      "for": "Juegas por (tu chapter)",
      "play": "Jugar",
      "best": "Tu récord esta semana: {n} puntos",
      "noBest": "Aún no has jugado esta semana.",
      "cup": "Chapter Cup",
      "cupNote": "Cada chapter suma las tres mejores puntuaciones de sus jugadores. El servidor reproduce cada partida para verificarla. Participan los nombres que empiecen por GDG, GDSC o WTM.",
      "cupOff": "La Chapter Cup solo está disponible en la web del juego.",
      "cupEmpty": "Aún no hay chapters esta semana: el primer puesto está libre.",
      "retro": "Reto semanal: {n} puntos",
      "sending": "Enviando y verificando…",
      "rank": "{chapter} va #{rank} en la Chapter Cup",
      "verified": "Verificado ✓ ({n} puntos) · tu récord: {best}",
      "notSent": "No enviado ({why}): inténtalo más tarde."
    },
    "medals": {
      "title": "Medallas",
      "new": "¡Nueva medalla!",
      "newMany": "¡Nuevas medallas!"
    },
    "kit": {
      "title": "El kit del chapter",
      "sub": "Cada estrella es una herramienta fija",
      "intro": "Gasta aquí las estrellas de la temporada: cada mejora sirve para todos los eventos, en solitario o en pareja. Cámbialas cuando quieras.",
      "left": "estrellas libres, de {total} obtenidas",
      "spend": "Tienes {n} estrellas para gastar en el kit del chapter",
      "open": "Abrir el kit"
    },
    "meters": {
      "budget": "Presupuesto",
      "rsvp": "RSVP",
      "community": "Comunidad",
      "partner": "Partners",
      "energy": "Energía"
    },
    "streams": {
      "Sede": "Sede",
      "Logistica": "Logística",
      "Speaker": "Speakers",
      "Sponsor": "Sponsors",
      "Community": "Comunidad",
      "Volontari": "Voluntarios",
      "Accoglienza": "Recepción",
      "Team": "Equipo"
    },
    "fx": {
      "budget": "{s}€{v}",
      "rsvp": "{s}{v} RSVP",
      "community": "{s}{v} comunidad",
      "partner": "{s}{v} partners",
      "energy": "{s}{v} energía",
      "vols": "+{v} voluntarios"
    },
    "set": {
      "networkCheck": "red verificada",
      "sponsorPack": "pack de patrocinio",
      "coLead": "co-organizador",
      "cocTeam": "contactos de CoC",
      "signage": "cartelería",
      "catering": "catering",
      "provaTecnica": "prueba técnica",
      "labReady": "Lab listo",
      "checkinQR": "check-in QR",
      "speakerCare": "speaker care",
      "backupSpeaker": "speaker de reserva",
      "lightningJolly": "comodín lightning",
      "waitlist": "lista de espera",
      "reminder": "recordatorios",
      "runOfShow": "escaleta del staff",
      "raffle": "sorteo",
      "fireCheck": "sin alarmas sorpresa",
      "pressReady": "prensa lista",
      "coffeePlus": "más café",
      "dogGate": "puerta vigilada",
      "venueKey": "llaves en mano",
      "timeKeeper": "tarjeta de tiempo",
      "streamTest": "stream probado",
      "vipReady": "bienvenida VIP",
      "kidsCorner": "zona infantil",
      "photoLanyards": "lanyards de fotos",
      "accessRoute": "ruta accesible",
      "mentors": "mentores",
      "restArea": "sala de descanso",
      "judgingRules": "reglas",
      "nightGuard": "seguridad nocturna"
    },
    "lo": {
      "eyebrow": "El día anterior · {chapter}",
      "title": "Esto es lo que tenéis",
      "people": "~{n}",
      "peopleSub": "asistentes esperados ({rsvp} RSVPs, {pct}%)",
      "vols": "voluntarios",
      "energy": "energía",
      "budget": "presupuesto",
      "sat": "satisfacción inicial",
      "staff": "El equipo",
      "box": "La caja del GDG",
      "prep": "Los preparativos",
      "missing": "falta",
      "go": "Abrir puertas",
      "wait": "El host abre las puertas.",
      "goals": "Objetivos de hoy",
      "controls": "Toca un problema para resolverlo · toca al co-org o voluntario, luego la tarea · teclado: WASD + Space"
    },
    "flags": {
      "checkinQR": "Check-in QR",
      "catering": "Catering confirmado",
      "speakerCare": "Speaker care",
      "backupSpeaker": "Speaker de reserva",
      "provaTecnica": "Prueba técnica",
      "networkCheck": "Red verificada",
      "labReady": "Lab preparado",
      "cocTeam": "Contactos de CoC",
      "runOfShow": "Escaleta del staff",
      "signage": "Cartelería",
      "raffle": "Sorteo final",
      "sponsorPack": "Pack de patrocinio",
      "fireCheck": "Sin alarmas sorpresa",
      "pressReady": "Prensa confirmada",
      "dogGate": "Puerta vigilada",
      "streamTest": "Stream probado",
      "vipReady": "Bienvenida VIP planeada",
      "timeKeeper": "Tarjeta de tiempo",
      "kidsCorner": "Zona infantil",
      "photoLanyards": "Lanyards de fotos",
      "accessRoute": "Ruta accesible",
      "mentors": "Mentores por turnos",
      "restArea": "Sala de descanso",
      "judgingRules": "Reglas públicas",
      "nightGuard": "Seguridad nocturna"
    },
    "hud": {
      "sat": "VALORACIÓN",
      "goals": "OBJETIVOS",
      "points": "PUNTOS",
      "combo": "COMBO ×{n}",
      "chat": "CHAT DEL STAFF",
      "forced": "descanso forzoso",
      "box": "CAJA GDG · toca para coger",
      "missing": "falta",
      "panic": "¡CAOS!",
      "rush": "HORA PUNTA",
      "open": "Puertas abiertas",
      "next": "Luego: {t}",
      "end": "Cierre",
      "closed": "CERRADO",
      "stage": "ESCENARIO",
      "late": "{m}' tarde",
      "starting": "Empieza ya…",
      "noSignal": "NO SIGNAL",
      "unread": "+{n}",
      "reply": "Responder"
    },
    "pause": {
      "title": "Pausa",
      "text": "El DevFest puede esperar. En la vida real, sería un lujo.",
      "resume": "Reanudar",
      "restart": "Reiniciar",
      "help": "Cómo jugar",
      "audioOn": "Sonido: sí",
      "audioOff": "Sonido: no",
      "menu": "Menú",
      "coachOn": "Consejos: sí",
      "coachOff": "Consejos: no"
    },
    "retro": {
      "goalOk": "HECHO",
      "goalNo": "FALLIDO",
      "paper": "La Gaceta del DevFest",
      "feedback": "Feedback {fb}/5",
      "points": "{n} puntos",
      "record": "¡nuevo récord!",
      "menu": "Menú",
      "again": "Rejugar",
      "next": "Próximo evento",
      "season": "Temporada",
      "leave": "Salir de la sala",
      "present": "asistentes",
      "onTime": "charlas a tiempo",
      "fixed": "resueltos",
      "prevented": "vistos a tiempo",
      "escaped": "se escaparon",
      "queue": "máx. en cola",
      "chat": "chats atendidos",
      "rush": "horas punta",
      "feel": "¿Cómo fue?",
      "feels": [
        "Agotado",
        "Orgulloso",
        "Caótico",
        "Divertido",
        "Tranquilo",
        "¡Otra vez!"
      ],
      "moments": "Momentos clave",
      "quiet": "Un día tranquilo. Sospechoso.",
      "lessons": "Conclusiones",
      "coach": "El coach",
      "group": "Para la retro del equipo",
      "commit": "Mi compromiso",
      "commitPh": "Una sola cosa, concreta",
      "copy": "Copiar para el chat de leads",
      "copied": "Copiado",
      "aiWriting": "Gemini está escribiendo la Gaceta…",
      "unlocked": "Desbloqueado: {ev}",
      "share": "🎟️ Overbooked! · {ev} {chapter}\n{stars} feedback {fb}/5 · {present} asistentes · {ontime} a tiempo",
      "shareFeel": "Cómo fue: {feel}",
      "shareLesson": "Lección: {lesson}",
      "shareCommit": "Mi compromiso: {commit}"
    },
    "forge": {
      "title": "La crisis de tu chapter",
      "intro": "Cuenta un problema real que hayas vivido. Se convertirá en una carta de tu Countdown para intercambiar con otros leads.",
      "story": "¿Qué pasó?",
      "storyPh": "El día antes nos quitaron la sala por una conferencia del rector…",
      "ai": "✨ Crear la carta con Gemini",
      "aiWorking": "Gemini está escribiendo…",
      "aiFail": "Gemini no responde: rellénala a mano.",
      "aiOff": "Gemini no está disponible aquí: rellénala a mano.",
      "manual": "O escríbela tú",
      "ctitle": "Título",
      "ctext": "Situación",
      "stream": "Área",
      "round": "Cuándo",
      "o": "Opción {n}",
      "cost": "Tardes",
      "effect": "Efecto",
      "cignore": "Si nadie se encarga",
      "tip": "Qué aprendiste",
      "save": "Añadir a mi baraja",
      "mine": "Tu baraja ({n})",
      "empty": "Aún no hay cartas.",
      "copy": "Copiar",
      "copied": "Copiado",
      "del": "Eliminar",
      "import": "Importar carta de otro chapter",
      "importPh": "Pega el texto copiado aquí",
      "importBtn": "Importar",
      "importErr": "Esta no es una carta de Overbooked!."
    },
    "common": {
      "back": "Atrás",
      "close": "Cerrar",
      "ok": "Entendido",
      "loading": "…"
    }
  },
  "roles": {
    "lead": {
      "name": "Lead",
      "blurb": "Gente y decisiones: sponsors, VIPs, salas llenas, Code of Conduct."
    },
    "tech": {
      "name": "Tech",
      "blurb": "Proyectores, micros, red, corriente. Lleva dos herramientas."
    },
    "host": {
      "name": "Bienvenida",
      "blurb": "Check-in, café, comida, acreditaciones. Y perretes."
    },
    "care": {
      "name": "Speaker care",
      "blurb": "Speakers perdidos, charlas que se alargan, escenarios."
    }
  },
  "tools": {
    "adattatori": {
      "name": "Adaptadores",
      "hint": "HDMI, USB-C, DisplayPort"
    },
    "batterie": {
      "name": "Pilas",
      "hint": "para los micros inalámbricos"
    },
    "ciabatte": {
      "name": "Regletas",
      "hint": "enchufes para el Lab"
    },
    "hotspot": {
      "name": "Hotspot",
      "hint": "red de reserva"
    },
    "badge": {
      "name": "Acreditaciones extra",
      "hint": "para los que vienen sin RSVP"
    },
    "crediti": {
      "name": "Créditos de Cloud",
      "hint": "claves de API de reserva"
    }
  },
  "rooms": {
    "A": "Sala principal",
    "B": "Sala B",
    "L": "Lab",
    "H": "Lobby",
    "R": "Control",
    "S": "Sala de speakers",
    "E": "Expo",
    "K": "Check-in"
  },
  "posts": {
    "checkin": "Check-in",
    "coffee": "Café",
    "info": "Info",
    "stageA": "Sala principal",
    "stageB": "Sala B",
    "lab": "Lab",
    "entrance": "Entrada",
    "sponsor1": "Expo",
    "kids": "Zona infantil",
    "tableA": "Mesas"
  },
  "stations": {
    "stageA": "el escenario del Aula Magna",
    "stageB": "el escenario de la Sala B",
    "lab": "el Lab",
    "coffee": "el café",
    "router": "el rack de red",
    "checkin": "el check-in",
    "entrance": "la entrada",
    "box": "la caja del GDG",
    "info": "el punto de información",
    "sponsor1": "el stand de patrocinadores",
    "sponsor2": "el stand de patrocinadores",
    "hall": "el vestíbulo",
    "expo": "la expo",
    "green": "la sala de speakers",
    "doorA": "la puerta del Aula Magna",
    "doorB": "la puerta de la Sala B",
    "phone": "el teléfono",
    "kids": "la zona infantil",
    "tableA": "las mesas del Aula Magna",
    "tableL": "las mesas del Lab"
  },
  "problems": {
    "kid": {
      "name": "Niño perdido",
      "how": "Llévalo de vuelta a la zona infantil."
    },
    "access": {
      "name": "Ruta accesible",
      "how": "Acompaña al invitado al Aula Magna."
    },
    "foto": {
      "name": "Foto sin permiso",
      "how": "Habla con el fotógrafo."
    },
    "mentor": {
      "name": "Equipo atascado",
      "how": "Un mentor a la mesa."
    },
    "noise": {
      "name": "Vecinos enfadados",
      "how": "Cálmalos en la entrada."
    },
    "queue": {
      "name": "Cola en el check-in",
      "how": "Mantén pulsado en el mostrador."
    },
    "stampante": {
      "name": "Impresora atascada",
      "how": "Mantén pulsado en el check-in."
    },
    "speaker": {
      "name": "Speaker en paradero desconocido",
      "how": "Búscalo y llévalo al escenario."
    },
    "hdmi": {
      "name": "Sin señal",
      "how": "Adaptadores y mantén pulsado en el escenario."
    },
    "mic": {
      "name": "Micrófono sin batería",
      "how": "Pilas y mantén pulsado."
    },
    "wifi": {
      "name": "Wi-Fi caído",
      "how": "Reinicia el rack en control o hotspot al Lab."
    },
    "prese": {
      "name": "Sin enchufes libres",
      "how": "Regletas al Lab."
    },
    "coffee": {
      "name": "Sin café",
      "how": "Mantén pulsado en la mesa del café."
    },
    "pizza": {
      "name": "Repartidor perdido",
      "how": "Ve a la entrada."
    },
    "overflow": {
      "name": "Sala llena",
      "how": "Mantén pulsado en la puerta: stream al vestíbulo."
    },
    "sponsor": {
      "name": "El sponsor te busca",
      "how": "Pásate por el stand."
    },
    "perso": {
      "name": "Asistente desorientado",
      "how": "Un segundo para indicarle el camino."
    },
    "coc": {
      "name": "Reporte de CoC",
      "how": "Solo staff, de inmediato y con calma."
    },
    "cancel": {
      "name": "El speaker no viene",
      "how": "Improvisa tú en el escenario."
    },
    "tavoli": {
      "name": "Reorganizar el Lab",
      "how": "Hacen falta dos personas."
    },
    "overrun": {
      "name": "El speaker se pasa de tiempo",
      "how": "Cartel de «5 minutos» desde el escenario."
    },
    "vip": {
      "name": "Visita sorpresa",
      "how": "El lead le da la bienvenida en la entrada."
    },
    "dog": {
      "name": "¡Un perro en la sala!",
      "how": "Atrápalo y llévalo fuera."
    },
    "press": {
      "name": "Prensa local",
      "how": "Entrevista en la zona expo: ¡oportunidad!"
    },
    "flame": {
      "name": "¿Tabuladores o espacios?",
      "how": "Separa la pelea."
    },
    "blackout": {
      "name": "Corte de luz",
      "how": "Rearma el cuadro en la sala de control."
    },
    "quota": {
      "name": "Límite de cuota de API",
      "how": "Créditos de Cloud en el Lab."
    },
    "stream": {
      "name": "Stream sin audio",
      "how": "Arregla el audio en la sala de control."
    },
    "badge": {
      "name": "Sin acreditaciones",
      "how": "Acreditaciones de sobra al check-in."
    }
  },
  "hints": {
    "kid": "🧸 Niño perdido: ve a por él y te seguirá a la zona infantil.",
    "access": "♿ Ve a por la invitada a la entrada y acompáñala al Aula Magna.",
    "mentor": "🧩 Equipo atascado: tócalo y el Tech irá el doble de rápido.",
    "hdmi": "📽️ ¿Portátil mudo? Adaptadores de la caja GDG (control) y mantén en el escenario.",
    "queue": "🧾 ¡Cola! Mantén pulsado en el check-in. Los voluntarios de allí van solos.",
    "tavoli": "🪑 El Lab requiere dos personas: toca a un voluntario y luego el Lab.",
    "wifi": "📡 Wi-Fi caído: reinicia el rack en control o pon zona wifi en el Lab.",
    "coc": "🛡️ Un reporte: es lo más grave. Ve ya.",
    "speaker": "🧭 Speaker perdido: ve a por él y te seguirá al escenario.",
    "dog": "🐕 ¡Un perro! Ve a por él: te seguirá hasta la entrada.",
    "press": "🎙️ Oportunidad: la entrevista sube la puntuación.",
    "overrun": "⏰ Se pasa de tiempo: mantén en el escenario, cartel de «5 minutos».",
    "chat": "💬 Chat del staff: toca una respuesta. Ignorarlo sale caro."
  },
  "events": {
    "wtm": {
      "name": "Women Techmakers IWD",
      "when": "Sábado por la tarde",
      "blurb": "Charlas, paneles y mentoría. La acogida es lo primero."
    },
    "hack": {
      "name": "Hackatón nocturno",
      "when": "Sábado por la noche",
      "blurb": "Dieciséis horas, treinta equipos, pizza a medianoche."
    },
    "meetup": {
      "name": "Meetup de los jueves",
      "when": "Jueves, 18:30",
      "blurb": "Dos charlas, una sala, cuarenta pizzas."
    },
    "studyjam": {
      "name": "Build with AI Study Jam",
      "when": "Sábado por la mañana",
      "blurb": "Codelabs en el Lab. El Wi-Fi es un mito."
    },
    "ioext": {
      "name": "Google I/O Extended",
      "when": "Viernes por la noche",
      "blurb": "Keynote en directo, sala a tope, VIP en camino."
    },
    "devfest": {
      "name": "DevFest",
      "when": "Sábado, todo el día",
      "blurb": "Tres salas, quince sesiones, Murphy."
    }
  },
  "breaks": {
    "coffee": "Coffee break",
    "lunch": "Comida",
    "pizza": "Pizza y networking",
    "dinner": "Cena buffet",
    "midnight": "Pizza de medianoche",
    "coffee4": "Café de las 4",
    "breakfast": "Desayuno"
  },
  "talks": {
    "wtmKeynote": "Keynote: la tech que creamos juntos",
    "wtmCareer": "Carreras no lineales en tech",
    "wtmAI": "IA responsable en la práctica",
    "wtmPanel": "Panel: liderazgo y comunidad",
    "wtmMentoring": "Círculos de mentoría",
    "wtmLeadership": "De dev a tech lead",
    "wtmPhoto": "Networking y foto de grupo",
    "hkKickoff": "Kickoff: reglas y equipos",
    "hkHackA": "Hackeo en el Aula Magna",
    "hkHackL": "Hackeo en el Lab",
    "hkMentors": "Clínica de mentores",
    "hkLate": "La charla de la 1: debug nocturno",
    "hkDemo": "Demos de los equipos",
    "hkAwards": "Premios",
    "meetupAI": "Gemini en tu editor",
    "meetupFlutter": "Una app Flutter en 40 minutos",
    "sjIntro": "Build with AI: kickoff",
    "sjLab1": "Codelab: tu primer agente",
    "sjPrompt": "Prompting para haters de los prompts",
    "sjLab2": "Codelab: Gemini en el navegador",
    "sjGemma": "Gemma en tu móvil",
    "ioKeynote": "Keynote de Google I/O en vivo",
    "ioAndroid": "Novedades en Android",
    "ioWeb": "Web: qué puedes usar hoy",
    "ioGemini": "Gemini: qué cambia para nosotros",
    "ioFirebase": "Firebase en una hora",
    "dfKeynote": "Keynote: comunidad en la era de los agentes",
    "dfAdk": "Agentes con ADK: del notebook a Cloud Run",
    "dfFlutter": "Flutter: una codebase, seis plataformas",
    "dfCodelab": "Codelab: Build with AI",
    "dfGemini": "Gemini en producción sin arruinarse",
    "dfA11y": "Accesibilidad: tu web no está lista",
    "dfGemma": "Gemma en tu móvil: IA on-device",
    "dfKmp": "Kotlin Multiplatform en el mundo real",
    "dfFirebase": "Taller: Firebase en una hora",
    "dfFrantoio": "Puse IA en la almazara de mi abuelo",
    "dfBaseline": "Web Baseline: qué usar hoy",
    "dfMonolith": "Del monolito a microservicios (y vuelta)",
    "dfPrompt": "Prompt engineering para haters de los prompts",
    "lightning": "Lightning talks de la comunidad",
    "raffle": "Sorteo y foto de grupo"
  },
  "cards": {
    "wtm_kids": {
      "title": "¿Quién cuida a los peques?",
      "text": "La mitad de las ponentes tiene peques.",
      "o": [
        "Zona infantil con monitorado",
        "Que se apañen las familias"
      ],
      "ignore": "Peques correteando por la sede.",
      "tipT": "Una zona infantil amplía tu público",
      "tipD": "Un espacio supervisado, juguetes y monitorado: las familias con peques por fin pueden venir. PyCon UK lo hace desde 2016."
    },
    "wtm_photo": {
      "title": "Fotos sí o fotos no",
      "text": "Quien hace las fotos llega a las 14:00.",
      "o": [
        "Lanyards de colores según consentimiento",
        "Un cartel en la entrada"
      ],
      "ignore": "Se fotografía a cualquiera.",
      "tipT": "Rojo: nada de fotos; verde: adelante",
      "tipD": "Los lanyards de colores avisan a la cámara de quién no quiere salir. Mozilla los usa en sus eventos."
    },
    "wtm_access": {
      "title": "El ascensor de la sede",
      "text": "Dicen que a veces se atasca.",
      "o": [
        "Visita técnica con alguien en silla de ruedas",
        "Pedir las llaves del montacargas"
      ],
      "ignore": "A rezar para que funcione.",
      "tipT": "La accesibilidad se comprueba antes",
      "tipD": "Recorridos, ascensores, baños, escenario: una visita con quien de verdad los usa detecta todo en una hora."
    },
    "wtm_speakers": {
      "title": "El cartel",
      "text": "Faltan dos ponentes y el tiempo vuela.",
      "o": [
        "Convocatoria abierta con mentoría para debutantes",
        "Invitar a caras conocidas"
      ],
      "ignore": "Un programa más corto.",
      "tipT": "Hay que impulsar voces nuevas",
      "tipD": "Una convocatoria con mentoría sube al escenario a quien jamás se habría postulado. Es la esencia de Women Techmakers."
    },
    "hk_mentors": {
      "title": "¿Quién ayuda a los equipos de noche?",
      "text": "Treinta equipos y nadie en pie a las 3 am.",
      "o": [
        "Fichar mentores por turnos",
        "Un par de colegas con experiencia"
      ],
      "ignore": "Los equipos se las apañan solos.",
      "tipT": "Los mentores hacen el hackatón",
      "tipD": "Sin mentores, un equipo se atasca horas. MLH los considera clave en el evento, incluso de noche."
    },
    "hk_food": {
      "title": "¿Hay comida?",
      "text": "Dieciséis horas, noventa personas.",
      "o": [
        "Pizza a medianoche y desayuno",
        "Snacks y máquinas de vending"
      ],
      "ignore": "Que cada cual traiga lo suyo.",
      "tipT": "Comida, Wi-Fi y enchufes",
      "tipD": "Lo básico que no puede faltar en un hackatón, según MLH. Pide según la cifra confirmada."
    },
    "hk_rest": {
      "title": "¿Quién duerme dónde?",
      "text": "A las 4 am alguien caerá frito.",
      "o": [
        "Sala de descanso con camillas",
        "Los pufs servirán"
      ],
      "ignore": "Pufs y chaquetas.",
      "tipT": "La noche se debe planificar",
      "tipD": "Una sala tranquila para descansar y turnos de staff: quien caiga a las 4 no expone a las 9."
    },
    "hk_rules": {
      "title": "Bases y premios",
      "text": "Los criterios del jurado no están por escrito.",
      "o": [
        "Criterios públicos desde el minuto uno",
        "Que el jurado decida sobre la marcha"
      ],
      "ignore": "Ya se verá al final.",
      "tipT": "Reglas claras, veredicto aceptado",
      "tipD": "Criterios públicos desde el inicio evitan quejas y malos rollos en la entrega de premios."
    },
    "hk_night": {
      "title": "La sede de noche",
      "text": "Conserjería cierra a las 22:00. El vecindario duerme.",
      "o": [
        "Permiso nocturno y seguridad",
        "Cruzar los dedos"
      ],
      "ignore": "Cruzar los dedos.",
      "tipT": "Pide el permiso nocturno con tiempo",
      "tipD": "Un hackatón nocturno exige sede abierta, seguridad y respetar el descanso del vecindario."
    },
    "sede": {
      "title": "Buscamos sede para 170 plazas",
      "text": "Hay que cerrar la fecha ya.",
      "o": [
        "Paraninfo de la universidad",
        "Centro de congresos"
      ],
      "ignore": "Parche de última hora, red inestable.",
      "tipT": "La sede se busca con meses de margen",
      "tipD": "GDG Spain tardó tres meses. La universidad es la aliada natural, pero revisa la red: 30 Mbps por cada 100 personas."
    },
    "sponsor": {
      "title": "1.500 € por la lista de emails",
      "text": "Un sponsor quiere los correos del público.",
      "o": [
        "Stand y logo, nada de datos",
        "Aceptamos, hace falta el dinero"
      ],
      "ignore": "El sponsor se marcha a otro lado.",
      "tipT": "Los datos no se venden",
      "tipD": "Compartir los emails de asistentes exige su consentimiento (GDPR). Ofrece a los sponsors visibilidad y 5-10 minutos en el escenario."
    },
    "team": {
      "title": "Tu bus factor es 1",
      "text": "Si te marchas, el chapter muere contigo.",
      "o": [
        "Fichar un co-organizer",
        "Involucrar al GDG on Campus"
      ],
      "ignore": "Todo a tus espaldas.",
      "tipT": "Un equipo pequeño pero real",
      "tipD": "Un gran evento se sostiene con 3-9 personas y una responsable por área. Hacerlo todo a solas te quema."
    },
    "promo": {
      "title": "Las inscripciones están paradas",
      "text": "Quedan ocho semanas.",
      "o": [
        "Invita: universidad, meetups, chapters",
        "Post patrocinado"
      ],
      "ignore": "Suben solas, pero poco.",
      "tipT": "Tres impactos antes de inscribirse",
      "tipD": "Promociona dos meses antes: la gente necesita ver el evento unas tres veces."
    },
    "volontari": {
      "title": "¿Quién ayuda el gran día?",
      "text": "Check-in, café, salas: faltan manos.",
      "o": [
        "Llamada con briefing de 30 min",
        "Pedírselo a unos amigos"
      ],
      "ignore": "Ese día estarás solo.",
      "tipT": "Mejor que sobren a que falten",
      "tipD": "Recluta voluntarios un mes antes. DevFest Ucrania: 30 voluntarios para 500 personas."
    },
    "cfp": {
      "title": "4 propuestas, todas de AI",
      "text": "El call for speakers no avanza.",
      "o": [
        "Pide ayuda a chapters cercanos y GDEs",
        "Amplía el CFP"
      ],
      "ignore": "Agenda monótona, menos asistentes.",
      "tipT": "Los speakers surgen de la comunidad",
      "tipD": "Dos charlas al mes son 24 speakers al año. DevFest Italia 2020 lo montaron diez GDGs juntos."
    },
    "coc": {
      "title": "¿Basta con poner el Code of Conduct?",
      "text": "Está enlazado. Nadie sabe qué hacer si hay un reporte.",
      "o": [
        "Dos personas formadas",
        "Con el enlace basta"
      ],
      "ignore": "El enlace se queda ahí.",
      "tipT": "El CoC es un protocolo",
      "tipD": "Staff visible, cada reporte atendido. PyCon 2019 recibió 13 reportes."
    },
    "diversita": {
      "title": "Nueve speakers, todos hombres",
      "text": "Alguien del público te lo señala.",
      "o": [
        "Buscar ponentes diversas",
        "Para el año que viene"
      ],
      "ignore": "El cartel se queda así.",
      "tipT": "La diversidad se prepara antes",
      "tipD": "Muchos DevFests fijan metas claras: Norteamérica 2018 apuntó a un 35% de ponentes mujeres."
    },
    "accesso": {
      "title": "Tres escalones y sin rampa",
      "text": "Alguien en silla de ruedas pregunta si puede entrar.",
      "o": [
        "Rampa y rutas señalizadas",
        "Ya veremos ese día"
      ],
      "ignore": "Nadie responde.",
      "tipT": "La accesibilidad se diseña",
      "tipD": "Entrada sin barreras, micros para preguntas, sala silenciosa: la guía SIGACCESS es un checklist básico."
    },
    "swag": {
      "title": "Las camisetas llegan el lunes",
      "text": "El DevFest es el sábado.",
      "o": [
        "Envío exprés",
        "Da igual, solo pegatinas"
      ],
      "ignore": "Sin camisetas.",
      "tipT": "El swag importa menos de lo que crees",
      "tipD": "El swag cuesta, llega tarde y no retiene a nadie: un buen almuerzo cunde más."
    },
    "sponsorvia": {
      "title": "El patrocinador se echa atrás",
      "text": "Tu contacto cambió de curro.",
      "o": [
        "Firmar el acuerdo ya",
        "La quesería local invita a comer"
      ],
      "ignore": "El dinero se esfuma.",
      "tipT": "Contratos firmados",
      "tipD": "Los sponsors se caen cuando su contacto interno se marcha. Sin contrato, el evento peligra."
    },
    "promotalk": {
      "title": "Una charla que parece teletienda",
      "text": "Un miembro quiere colar su producto.",
      "o": [
        "Proponerle una charla técnica",
        "Aceptar (paga 200 €)"
      ],
      "ignore": "La charla sigue adelante.",
      "tipT": "Nada de ventas desde el escenario",
      "tipD": "Los GDGs son sin ánimo de lucro e independientes: ni formación de pago ni ventas camufladas."
    },
    "catering": {
      "title": "¿Cuántos almuerzos pedimos?",
      "text": "El catering quiere una cifra para el viernes.",
      "o": [
        "75-80% de confirmados, cerrado",
        "Pedir pizzas ese mismo día"
      ],
      "ignore": "Ya improvisaremos.",
      "tipT": "Pide para los que de verdad van",
      "tipD": "En eventos gratis falla entre el 28% y el 50%. Pide comida para el 75-80% de la asistencia estimada."
    },
    "kitav": {
      "title": "La caja: audio y vídeo",
      "text": "Cada speaker trae un portátil distinto.",
      "o": [
        "Adaptadores y pilas",
        "Solo adaptadores"
      ],
      "ignore": "Una caja medio vacía.",
      "tipT": "El kit salva vidas",
      "tipD": "Portátil, proyector y micro que no se entienden: la avería clásica del directo."
    },
    "kitlab": {
      "title": "El Lab del codelab",
      "text": "24 portátiles a tope durante dos horas.",
      "o": [
        "Regletas y un hotspot",
        "Revisar la red con IT"
      ],
      "ignore": "Ya se verá en el Lab.",
      "tipT": "Dimensiona la red para el pico",
      "tipD": "Mínimo 30 Mbps por cada 100 personas, con un 20-30% de margen para el cuarto de hora punta."
    },
    "prova": {
      "title": "¿Prueba técnica el viernes noche?",
      "text": "Cansancio total y curro hasta las 18:00.",
      "o": [
        "Prueba completa con IT",
        "Montar solo el Lab"
      ],
      "ignore": "Sorpresa el sábado.",
      "tipT": "El viernes te salva el sábado",
      "tipD": "Staff 15 minutos antes con checklist; 5 minutos entre charlas nunca son suficientes."
    },
    "checkin": {
      "title": "150 personas en media hora",
      "text": "La mitad llega entre las 9:00 y las 9:30.",
      "o": [
        "QR y acreditaciones preimpresas",
        "Lista impresa"
      ],
      "ignore": "Lista impresa.",
      "tipT": "El check-in es el primer recuerdo",
      "tipD": "Hacer check-in en la plataforma da la asistencia oficial. 1.000 personas con 15 voluntarios: hora y media."
    },
    "badgekit": {
      "title": "¿Y si viene gente sin registrarse?",
      "text": "Vendrán. Siempre pasa.",
      "o": [
        "Acreditaciones extra en la caja",
        "Escribir a mano"
      ],
      "ignore": "Sin acreditaciones extra.",
      "tipT": "Gente sin RSVP",
      "tipD": "Un montón de acreditaciones en blanco y rotuladores evita la cola dentro de la cola."
    },
    "speakercare": {
      "title": "¿Saben los speakers adónde ir?",
      "text": "Vienen de tres regiones distintas.",
      "o": [
        "Email con mapa y contacto",
        "Está el grupo de WhatsApp"
      ],
      "ignore": "Ya se apañarán.",
      "tipT": "Speakers bien acogidos, charlas puntuales",
      "tipD": "Pide a los speakers que lleguen 15-20 minutos antes, con un contacto y un mapa."
    },
    "riserva": {
      "title": "¿Y si se cae un speaker?",
      "text": "Pasa siempre. Lo que no sabes es quién.",
      "o": [
        "Una charla de reserva lista",
        "Comodín de lightning talk"
      ],
      "ignore": "Ya se verá.",
      "tipT": "Cuenta con alguna baja",
      "tipD": "Al menos un speaker no aparece. Prepara la charla de reserva igual que el resto."
    },
    "overbooking": {
      "title": "Más inscritos que asientos",
      "text": "¿Cerrar o dejarlo abierto?",
      "o": [
        "1,5× aforo + lista de espera",
        "Dejarlo abierto"
      ],
      "ignore": "Sigue abierto.",
      "tipT": "Haz overbooking con cabeza",
      "tipD": "Para eventos gratis, admite un 1,5-1,7× del aforo. Una fianza reembolsable mejora la asistencia."
    },
    "antincendio": {
      "title": "¿Mantenimiento en el recinto?",
      "text": "Nadie pidió el calendario de la sede.",
      "o": [
        "Preguntar al recinto",
        "Qué podría salir mal"
      ],
      "ignore": "Nadie pregunta.",
      "tipT": "El calendario del recinto",
      "tipD": "Simulacros, limpieza, cierres: el recinto tiene horarios que no sabrás hasta que preguntes."
    },
    "stampa": {
      "title": "La prensa local quiere venir",
      "text": "Buscan a alguien a quien entrevistar.",
      "o": [
        "Preparar a un portavoz",
        "Si vienen, ya veremos"
      ],
      "ignore": "Ya veremos.",
      "tipT": "La prensa es una oportunidad",
      "tipD": "Un artículo local atrae inscritos y sponsors para el próximo año: ten a alguien listo para hablar."
    },
    "reminder": {
      "title": "Quedan siete días",
      "text": "Muchos inscritos ya ni se acuerdan.",
      "o": [
        "Recordatorio: «¿no vienes? libera tu plaza»",
        "Una story de Instagram"
      ],
      "ignore": "Sin recordatorios.",
      "tipT": "Los recordatorios llenan salas",
      "tipD": "Los avisos personales reducen bajas. Las entradas vuelan las últimas 72 h: cierra a tiempo para el catering."
    },
    "runofshow": {
      "title": "¿Quién hace qué, minuto a minuto?",
      "text": "Hay agenda, pero no un minutado para el staff.",
      "o": [
        "Minutado y un líder por zona",
        "Sobre la marcha"
      ],
      "ignore": "Sin minutado.",
      "tipT": "Un responsable por zona",
      "tipD": "Las vías de comunicación crecen a N(N-1)/2: un minutado compartido evita que todo pase por una persona."
    },
    "premi": {
      "title": "Los sponsors mandan swag",
      "text": "Camisetas, pegatinas, dos smartwatches.",
      "o": [
        "Sorteo al final del día",
        "Swag en el check-in"
      ],
      "ignore": "Se queda en la sala técnica.",
      "tipT": "Las tardes se vacían",
      "tipD": "Tras comer, parte del público se marcha. Darles un motivo para quedarse mantiene las salas llenas."
    },
    "segnaletica": {
      "title": "El recinto es un laberinto",
      "text": "Tres plantas, dos entradas, cero carteles.",
      "o": [
        "Carteles y un mapa",
        "Los voluntarios se encargan"
      ],
      "ignore": "Sin carteles.",
      "tipT": "La gente se pierde",
      "tipD": "La gente perdida para al staff a cada paso. Poner carteles cuesta muy poco."
    },
    "bar": {
      "title": "La cafetería cierra a las 12",
      "text": "¿Y por la tarde?",
      "o": [
        "Alquilar cafeteras",
        "Con el bar basta"
      ],
      "ignore": "Con el bar basta.",
      "tipT": "El café es infraestructura",
      "tipD": "En la pausa del café surge el networking. Y es donde el staff recarga pilas."
    },
    "calendario": {
      "title": "El mismo día que otro DevFest cercano",
      "text": "Te enteras por un post de LinkedIn.",
      "o": [
        "Coordinarse: speakers y promo",
        "Que gane el mejor"
      ],
      "ignore": "El público se divide.",
      "tipT": "El calendario es de todos",
      "tipD": "En 2025 coincidieron tres DevFest italianos el mismo día. Un calendario compartido evita choques."
    },
    "stanchezza": {
      "title": "Llevas días sin dormir",
      "text": "Trabajo, DevFest, trabajo, DevFest.",
      "o": [
        "Tómate un finde libre",
        "Aprieta los dientes"
      ],
      "ignore": "Aprieta los dientes.",
      "tipT": "El burnout es el verdadero riesgo",
      "tipD": "«Mucho más trabajo que diversión», escribe quien lo hizo durante cinco años. Strange Loop cerró por agotamiento."
    },
    "cani": {
      "title": "El local da a un parque",
      "text": "Perros por todos lados, puertas abiertas.",
      "o": [
        "Un voluntario en la puerta",
        "Son monos, va"
      ],
      "ignore": "Puertas abiertas.",
      "tipT": "Quién vigila la entrada",
      "tipD": "Por la entrada entra todo: gente, proveedores, sorpresas. Alguien tiene que vigilarla."
    },
    "m_pizza": {
      "title": "¿Cuarenta pizzas o sesenta?",
      "text": "70 apuntados, 50 sitios.",
      "o": [
        "Pide para los asistentes, a hora fija",
        "Llamamos a las 20:00"
      ],
      "ignore": "Llamamos a las 20:00.",
      "tipT": "Pizza para quien esté allí",
      "tipD": "Un meetup cuesta 100-250 € al mes en comida. Pide según la asistencia prevista, no los inscritos."
    },
    "m_porta": {
      "title": "¿Quién abre el local a las 18?",
      "text": "El conserje tiene las llaves. Hasta las 17.",
      "o": [
        "Queda con él y pide las llaves",
        "A ver si se queda"
      ],
      "ignore": "Todos esperando fuera.",
      "tipT": "Todo local tiene su conserje",
      "tipD": "Doce locales al año son doce conserjes a los que conocer por su nombre."
    },
    "m_promo": {
      "title": "El post del meetup tiene 3 likes",
      "text": "Quedan diez días.",
      "o": [
        "Escribe a asistentes anteriores",
        "Vuelve a publicarlo"
      ],
      "ignore": "Siguen siendo 3 likes.",
      "tipT": "Quien ya vino, vuelve",
      "tipD": "Hacer crecer un meetup lleva años de citas periódicas. Empieza por quienes ya vinieron."
    },
    "m_speaker": {
      "title": "El speaker pide 90 minutos",
      "text": "El slot es de 40.",
      "o": [
        "Avisos de tiempo y moderador",
        "Que hable"
      ],
      "ignore": "Hablará lo que le dé la gana.",
      "tipT": "Las charlas se alargan",
      "tipD": "5 minutos entre charlas nunca bastan: alguien tiene que controlar el tiempo."
    },
    "sj_quota": {
      "title": "El codelab usa la API de Gemini",
      "text": "Treinta personas, una sola key.",
      "o": [
        "Créditos y keys de reserva",
        "Que cada uno use la suya"
      ],
      "ignore": "Cada uno usa la suya.",
      "tipT": "La cuota siempre se agota en vivo",
      "tipD": "En un codelab todos llaman a la misma API al mismo minuto: prepara créditos e instrucciones para keys personales."
    },
    "sj_aule": {
      "title": "24 sitios en el Lab, 60 inscritos",
      "text": "Todos quieren codelab.",
      "o": [
        "Dos turnos y lista de espera",
        "Que se aprieten"
      ],
      "ignore": "Que se aprieten.",
      "tipT": "Los sitios reales tienen enchufe",
      "tipD": "En un codelab el límite no son las sillas: son los enchufes y la red."
    },
    "io_stream": {
      "title": "La keynote en directo",
      "text": "Proyector, audio, streaming desde la otra punta del mundo.",
      "o": [
        "Prueba con un vídeo de 2 horas",
        "Ya funcionará"
      ],
      "ignore": "Ya funcionará.",
      "tipT": "El streaming se prueba",
      "tipD": "Audio, red y proyector se prueban juntos y con tiempo: los fallos salen en el minuto 40."
    },
    "io_vip": {
      "title": "El concejal quiere saludar",
      "text": "Cinco minutos. En teoría.",
      "o": [
        "Pacta la hora y la duración",
        "Improvisamos"
      ],
      "ignore": "Vendrá cuando le plazca.",
      "tipT": "Recibe a las instituciones",
      "tipD": "Un saludo institucional ayuda a la comunidad, si se acuerdan antes la hora y la duración."
    }
  },
  "chat": {
    "fx": {
      "parking": [
        "El speaker entra por el lado correcto: no se perderá.",
        "Sigue las señales: crucemos los dedos.",
        "Sin respuesta: el speaker se perderá por el recinto."
      ],
      "adapter": [
        "Adaptador listo en el escenario: nada de pantalla negra.",
        "Se apañará: no le quites el ojo al escenario.",
        "Sin respuesta: llegará sin adaptador."
      ],
      "logo": [
        "Logo arreglado: el sponsor está contento.",
        "Al sponsor no le convence.",
        "Sin respuesta: el sponsor viene a quejarse."
      ],
      "coffeeLow": [
        "Más café en camino.",
        "El café se acabará pronto.",
        "Sin respuesta: el café se acabará pronto."
      ],
      "queueHelp": [
        "Un voluntario corre al check-in.",
        "La cola se hace más larga.",
        "Sin respuesta: la cola se hace larguísima."
      ],
      "pizzaTime": [
        "Pedido confirmado: la pizza llega a tiempo.",
        "A ver si llega a tiempo.",
        "Sin respuesta: a ver si llega a tiempo."
      ],
      "wifiPass": [
        "Contraseña compartida: gente contenta.",
        "Respuesta vaga, pero cuela.",
        "Sin respuesta: la gente se queja."
      ],
      "vipCall": [
        "Bienvenida lista: el VIP llega tranquilo.",
        "A ver cómo sale.",
        "Sin respuesta: el VIP se presenta sin avisar."
      ],
      "mom": [
        "Mamá se queda tranquila y tú recargas pilas.",
        "Mamá se conforma.",
        "Mamá volverá a llamar luego."
      ],
      "lostThing": [
        "Objeto encontrado: sube la puntuación.",
        "En fin.",
        "Sin respuesta: el asistente se queda decepcionado."
      ],
      "kidsWhere": [
        "Zona infantil indicada: ningún peque perdido.",
        "A ver qué tal.",
        "Sin respuesta: el padre se queda decepcionado."
      ],
      "teamStuck": [
        "Mentor en camino: el equipo se pone en marcha.",
        "El equipo se apaña a duras penas.",
        "Sin respuesta: el equipo sigue atascado."
      ]
    },
    "acts": {
      "kidsWhere": [
        {
          "from": "Asistente",
          "text": "¿Dónde está la zona infantil? Mi hija quiere jugar",
          "r": [
            "Te acompaña alguien del equipo",
            "Al fondo de la zona expo"
          ]
        },
        {
          "from": "Elisa (speaker)",
          "text": "¿Puedo dejar al peque en algún sitio durante mi charla?",
          "r": [
            "Sí, hay zona infantil",
            "Tráelo a la sala"
          ]
        }
      ],
      "teamStuck": [
        {
          "from": "Equipo 7",
          "text": "El deploy lleva dos horas fallando, ¿algún mentor libre?",
          "r": [
            "Va un mentor para allá",
            "Probad a reiniciar"
          ]
        },
        {
          "from": "Equipo 3",
          "text": "Necesitamos ayuda con las API, estamos atascados",
          "r": [
            "Os mando a alguien",
            "Leed la docu"
          ]
        }
      ],
      "parking": [
        {
          "from": "Sara (speaker)",
          "text": "Estoy en el parking, ¿por dónde entro? 🚗",
          "r": [
            "Entrada lateral, voy a buscarte",
            "¡Sigue los carteles!"
          ]
        },
        {
          "from": "Marco (speaker)",
          "text": "El GPS me lleva a un descampado. ¿Es normal?",
          "r": [
            "Te mando ubicación y a un voluntario",
            "Pregunta en el bar"
          ]
        }
      ],
      "adapter": [
        {
          "from": "Davide (speaker)",
          "text": "Solo tengo USB-C. ¿Tenéis un adaptador HDMI?",
          "r": [
            "Te lo llevo al escenario",
            "Pregunta al público"
          ]
        },
        {
          "from": "Anna (speaker)",
          "text": "Mi portátil no detecta el proyector 😰",
          "r": [
            "Voy con el kit",
            "Reinicia y reza"
          ]
        }
      ],
      "logo": [
        {
          "from": "Sponsor",
          "text": "Nuestro logo en las diapositivas de apertura se ve muy pequeño",
          "r": [
            "Lo aumento ahora mismo",
            "Después de comer"
          ]
        }
      ],
      "coffeeLow": [
        {
          "from": "Luca (voluntario)",
          "text": "El café se está acabando ☕☕☕",
          "r": [
            "Abre la reserva en control",
            "Raciónalo"
          ]
        }
      ],
      "queueHelp": [
        {
          "from": "Giada (check-in)",
          "text": "¡¡¡Estamos desbordados en el check-in, ayuda!!!",
          "r": [
            "Te mando un voluntario",
            "Aguanta 5 minutos"
          ]
        }
      ],
      "pizzaTime": [
        {
          "from": "Pizzería",
          "text": "¿A qué hora queréis las pizzas? ¿Dirección exacta?",
          "r": [
            "12:30, entrada principal",
            "Luego os llamo"
          ]
        }
      ],
      "wifiPass": [
        {
          "from": "Asistente",
          "text": "¿Cuál es la contraseña del Wi-Fi?",
          "r": [
            "¡Está detrás de tu acreditación!",
            "Pregunta en el punto de información"
          ]
        }
      ],
      "vipCall": [
        {
          "from": "Ayuntamiento",
          "text": "El concejal se pasará a las 11 a saludar",
          "r": [
            "Lo recibimos en la entrada",
            "Vale, ya veremos"
          ]
        }
      ],
      "mom": [
        {
          "from": "Mamá",
          "text": "¿Has comido? Te vi en Instagram, se te ve cansado",
          "r": [
            "Sí mamá ❤️",
            "Luego"
          ]
        }
      ],
      "lostThing": [
        {
          "from": "Asistente",
          "text": "He perdido el cargador del portátil en la Sala B",
          "r": [
            "Lo buscamos, pásate por el punto de info",
            "Prueba en el bar"
          ]
        }
      ]
    },
    "noise": [
      {
        "from": "Luca (voluntario)",
        "text": "¿Quién se ha llevado las llaves de la Sala B?"
      },
      {
        "from": "Giada (check-in)",
        "text": "Un chico dice que está registrado pero no sale en la lista 🙃"
      },
      {
        "from": "Fotógrafo",
        "text": "Necesito a alguien para la foto del público a las 16"
      },
      {
        "from": "Sponsor",
        "text": "¿Quedan más tote bags? Se nos han terminado"
      },
      {
        "from": "Paolo (speaker)",
        "text": "¿Puedo hacer demo en vivo? Necesito buen internet"
      },
      {
        "from": "Co-org",
        "text": "¿Quién tiene el cargador del micro?"
      },
      {
        "from": "Conserje",
        "text": "A las 18:30 cierro, aviso"
      },
      {
        "from": "Luca (voluntario)",
        "text": "Se acabaron las chapas 😭"
      },
      {
        "from": "Asistente",
        "text": "¿Se puede aparcar en el patio?"
      },
      {
        "from": "Giada (check-in)",
        "text": "Acreditación de Juan Pérez impresa tres veces. Tres Juan Pérez distintos."
      },
      {
        "from": "Co-org",
        "text": "El grupo de Telegram ha explotado, 300 mensajes"
      },
      {
        "from": "Catering",
        "text": "Dejamos las botellas de agua en la entrada"
      },
      {
        "from": "Sara (speaker)",
        "text": "¿Puedo cambiar el orden de las slides a última hora?"
      },
      {
        "from": "Voluntaria",
        "text": "No hay papel en el baño (yo solo aviso)"
      },
      {
        "from": "Fotógrafo",
        "text": "La luz en el Aula Magna es un desastre"
      },
      {
        "from": "Asistente",
        "text": "¿Hay sala de lactancia?"
      },
      {
        "from": "Sponsor",
        "text": "Se nos ha caído el roll-up. Otra vez."
      },
      {
        "from": "Co-org",
        "text": "¡¡No os olvidéis de las fotos para redes!!"
      }
    ],
    "from": {
      "volunteer": "Voluntario",
      "speaker": "Speaker",
      "sponsor": "Sponsor",
      "pizzeria": "Pizzería",
      "attendee": "Asistente",
      "city": "Ayuntamiento",
      "mom": "Mamá"
    }
  },
  "banter": [
    "Disculpa, ¿dónde está la Sala B?",
    "¿El Wi-Fi?",
    "¿Queda café?",
    "¿Me imprimes la acreditación?",
    "¿Vais a compartir las diapositivas?",
    "¿Dónde está el baño?",
    "¿Hay pegatinas?",
    "¿Una pregunta rápida?",
    "¿A qué hora se come?",
    "¿La charla de AI está llena?",
    "¿Tienes un cargador?",
    "¡Qué buena organización!",
    "¿Nos hacemos una foto?",
    "¿Dónde están las camisetas?"
  ],
  "chaos": {
    "firedrill": {
      "title": "¡Alarma de incendios!",
      "text": "Un simulacro sorpresa: todos fuera unos minutos."
    },
    "firedrillEnd": "Falsa alarma: para adentro. Las charlas van con retraso."
  },
  "radio": {
    "hostPaused": "El host pausó la partida.",
    "kid": "🧸 ¡Un peque se escapó del rincón infantil!",
    "access": "♿ El ascensor no va: alguien necesita la ruta accesible.",
    "noise": "📢 ¡Los vecinos se quejan del ruido!",
    "locked": "Puerta cerrada: nadie avisó al conserje. Viene de camino…",
    "unlocked": "¡Llegó el conserje: abrimos!",
    "open": "¡Puertas abiertas! Check-in abajo a la derecha; la caja GDG, en control.",
    "controls": "Toca un problema: vas directo y lo arreglas.",
    "controlsDuo": "J1: WASD + Espacio. J2: flechas + Enter.",
    "speakerLost": "{name} no está en la sala de ponentes: búscalo y llévalo al escenario.",
    "coc": "Alguien pide ayuda por una conducta inapropiada. Ve de inmediato.",
    "cancel": "No llega quien daba la charla de las {t}. ¡Improvisa!",
    "pizza": "El repartidor da vueltas al edificio: ve a la entrada.",
    "escalate": "{p}: demasiado tarde.",
    "noTool": "{tool}: no está en la caja.",
    "late": "Empezamos con retraso: {t}",
    "talkCancel": "Charla cancelada: «{t}».",
    "lunchLate": "El almuerzo llega tarde y frío.",
    "lunch": "¡A comer!",
    "murphy": "😈 ¡Murphy ha entrado: páralo antes de que llegue a {where}!",
    "sabotage": "😈 Murphy atacó: {where}.",
    "burnout": "😵‍💫 Burnout: la organización también necesita descansar.",
    "raffle": "🎁 ¡Sorteo!",
    "photo": "📸 ¡Foto de grupo!",
    "synergy": "🤝 Dos pares de manos van más rápido.",
    "backup": "🦸 El suplente salva la charla.",
    "improvised": "🎤 Charla improvisada: ¡ovación!",
    "leave": "🚶 {n} personas se van ({why}).",
    "why": {
      "coda": "la cola",
      "overflow": "sala llena",
      "afternoon": "después de comer"
    },
    "stream": "📺 Streaming puesto en el vestíbulo.",
    "assign": "¿A dónde? Toca un problema o un puesto (círculos verdes).",
    "orgPick": "¿A dónde mandas a {name}? Toca un problema.",
    "orgSent": "{name} se encarga.",
    "volSent": "Un voluntario va a: {post}.",
    "volCant": "Los voluntarios no saben hacer esto: ve tú o envía al co-org.",
    "end": "🎉 ¡Se acabó! Se apagan las luces, arden los chats.",
    "paused": "⏸️ En pausa por el host.",
    "guest": "Estás en el evento del host.",
    "dog": "🐕 ¡Se ha colado un perro en la sala!",
    "vip": "🎖️ ¡Visita sorpresa en la entrada!",
    "press": "🎙️ La prensa local está en la expo.",
    "blackout": "💡 ¡Corte de luz en {where}!",
    "panic": "Demasiado a la vez: respira, elige, delega.",
    "chatMissed": "Mensaje ignorado: {who}.",
    "abilityNone": "No hay fallos técnicos que arreglar ahora: el hotfix sigue cargado.",
    "rush": "¡Hora punta! {n} marrones a la vez: soluciónalos antes de que empeoren.",
    "rushWon": "¡Hora punta superada! La valoración sube como la espuma.",
    "rushLost": "Hora punta perdida: la próxima pegará más fuerte."
  },
  "quips": {
    "fixed": [
      "¡Arreglado!",
      "¡Hecho!",
      "¡Genial!",
      "¡Solucionado!"
    ],
    "hdmi": [
      "¡Hay señal!",
      "¡Se ve!"
    ],
    "wifi": [
      "Reiniciado y listo.",
      "¡Hay conexión!"
    ],
    "coffee": [
      "¡Café!"
    ],
    "pizza": [
      "¡Llegó la pizza!"
    ],
    "speaker": [
      "¡Encontrado!",
      "¡Al escenario!"
    ],
    "dog": [
      "¡Buen perro!"
    ],
    "press": [
      "¡En portada!"
    ],
    "flame": [
      "Paz firmada."
    ],
    "prevent": [
      "¡A tiempo!"
    ],
    "escalate": [
      "¡Tarde!",
      "¡Ay!"
    ],
    "found": "¡Te pillé!",
    "murphy": "¡Murphy neutralizado!"
  },
  "lessons": {
    "kids": [
      "Una zona infantil de verdad",
      "Sin un espacio atendido, los peques corretean por la sede. Una animadora y alguien voluntario lo cambian todo."
    ],
    "access": [
      "La accesibilidad se prepara antes",
      "Una visita con alguien en silla de ruedas detecta en una hora lo que el día del evento saldría carísimo."
    ],
    "photo": [
      "Consentimiento de fotos",
      "Lanyards de colores: rojo sin fotos, amarillo pregunta, verde ok. El fotógrafo lo sabe desde el primer disparo."
    ],
    "mentors": [
      "Los mentores hacen el hackathon",
      "Sin mentores, los equipos se atascan durante horas. Hacen falta turnos, también de noche."
    ],
    "night": [
      "La noche hay que organizarla",
      "Turnos, sala de descanso y comida real: la segunda mitad de la noche decide las demos."
    ],
    "rules": [
      "Reglas y criterios públicos",
      "Si los criterios se deciden sobre la marcha, alguien va a impugnar el veredicto."
    ],
    "hdmiKit": [
      "Un kit de adaptadores cuesta menos que una charla cancelada",
      "Cada portátil sin señal costó minutos: {n} veces hoy."
    ],
    "hdmiStage": [
      "Deja el kit en la sala",
      "Había adaptadores, pero en la cabina de control. Un kit por sala lo agiliza todo."
    ],
    "speakers": [
      "A los ponentes hay que recibirlos",
      "Email con mapa, llegada 15-20 min antes y un voluntario en el punto de información."
    ],
    "backup": [
      "Un ponente de reserva, a punto",
      "Cuenta con alguna baja: un reserva convierte un hueco vacío en una charla."
    ],
    "queue": [
      "El check-in es la primera impresión",
      "La cola llegó a {n}. QR y dos voluntarios desde las 8:45."
    ],
    "wifi": [
      "Dimensiona la red para el pico",
      "30 Mbps por cada 100 personas, acordados con IT, más un hotspot de respaldo."
    ],
    "lunch": [
      "El almuerzo se confirma la víspera",
      "El 75-80% del aforo esperado, a una hora fija."
    ],
    "coc": [
      "Cada reporte merece respuesta inmediata",
      "Personas de contacto reconocibles, formadas y un protocolo que el staff conozca."
    ],
    "cocOk": [
      "El CoC funcionó",
      "Alguien supo qué hacer. Para eso sirve la formación."
    ],
    "burnout": [
      "Quien organiza también necesita pausas",
      "Hacer turnos y un café para el staff no son ningún lujo."
    ],
    "tavoli": [
      "Hay cosas que no se hacen en solitario",
      "Delegar y preparar todo la noche anterior evita quedarse atascado."
    ],
    "delegate": [
      "Reubica a tus voluntarios",
      "La delegación se adapta al día: check-in por la mañana, café en los descansos."
    ],
    "novols": [
      "Ningún evento sobrevive sin ayuda",
      "Sin voluntarios, te comiste todas las colas. Se reclutan con un mes de antelación."
    ],
    "overflow": [
      "Haz overbooking con cabeza",
      "Lista de espera, recordatorios y streaming entre salas."
    ],
    "murphy": [
      "Murphy no perdona",
      "Algo va a fallar de todos modos: un cronograma del staff lo ve venir antes."
    ],
    "afternoon": [
      "La tarde se va vaciando",
      "{n} personas se fueron antes de tiempo: dales una razón para quedarse."
    ],
    "turnout": [
      "Las salas se llenan meses antes",
      "{n} personas en la sala: promociona dos meses antes, contando con las bajas."
    ],
    "chat": [
      "El chat es la mitad del trabajo",
      "{n} mensajes ignorados: cada uno era un marrón en camino."
    ],
    "clean": [
      "Una jornada impecable",
      "La preparación dio sus frutos. Ahora apunta lo que funcionó."
    ],
    "interrupt": [
      "Todo el mundo busca al lead",
      "Te pararon {n} veces: puntos de información y carteles liberan al staff."
    ]
  },
  "retro": {
    "h3": [
      "{ev} {city}: ovación de pie",
      "{present} personas, {ontime} charlas a tiempo y un equipo con un plan."
    ],
    "h2": [
      "{ev} {city}: algún tropiezo, mucha comunidad",
      "El público sale feliz; el equipo, un poco menos descansado."
    ],
    "h1": [
      "Caos en {ev} {city}, pero la comunidad aguanta",
      "El día termina, por los pelos. Mañana, retrospectiva."
    ],
    "h0": [
      "{ev} {city}: para olvidar",
      "«Nunca más sin adaptadores», jura el equipo."
    ],
    "few": [
      "{ev} {city}: genial, pero para pocos",
      "Feedback {fb}, pero solo {present} en la sala: las estrellas también se ganan con difusión."
    ],
    "anon": {
      "h3": "{ev}: una ovación de pie",
      "h2": "{ev}: algún bache, pero mucha comunidad",
      "h1": "Caos en {ev}, pero la comunidad resiste",
      "h0": "{ev}: para olvidar",
      "few": "{ev}: genial, pero para pocos"
    },
    "q": [
      "¿Cuál fue el momento más caótico? ¿Os ha pasado en la vida real?",
      "¿Qué hay hoy en la caja de vuestro chapter?",
      "¿Qué problema decidisteis ignorar a propósito?",
      "Si pudierais repetir los preparativos, ¿qué cambiaríais?"
    ],
    "qBurnout": "¿Quién acabó quemado y por qué?",
    "qChat": "¿Cuántos mensajes ignorasteis? ¿Quién responde al chat el día del evento?"
  },
  "coach": {
    "welcome": [
      "¡Te damos la bienvenida!",
      "El juego se pausa cuando pasa algo nuevo. Lee con calma y pulsa Entendido (o Enter)."
    ],
    "you": [
      "Este eres tú",
      "Toca el mapa para moverte (teclado: WASD o flechas). Si tocas un problema, vas y lo arreglas tú."
    ],
    "checkin": [
      "Check-in",
      "La gente llega aquí. Si hay cola, toca el mostrador: te quedas ahí y das paso."
    ],
    "goals": [
      "Objetivos de hoy",
      "{list}. Cada uno vale una estrella: desbloquean el próximo evento y el kit del chapter."
    ],
    "rating": [
      "La valoración",
      "Sube si todo va sobre ruedas y baja si empeora un problema o cae una charla. Cuenta al final."
    ],
    "problem": [
      "¡Un problema!",
      "El anillo es el tiempo antes de que empeore. Toca el icono: vas y lo arreglas. El arco verde es el progreso."
    ],
    "tool": [
      "Falta una herramienta",
      "{tool}: está en la caja del GDG, en Control (abajo a la izquierda). Toca el problema y la coges de paso: es más rápido."
    ],
    "noTool": [
      "Herramienta ausente",
      "Nadie metió {tool} en la caja durante el Countdown. Puedes improvisar, pero tardarás más: prepárala la próxima vez."
    ],
    "crew": [
      "Necesitas ayuda",
      "Esto es cosa de dos: trae a un voluntario (tócalo y luego toca el sitio) o colabora con tu coorganizador."
    ],
    "warn": [
      "El triángulo amarillo",
      "Un problema a punto de estallar. Písalo antes de que salte y lo evitarás: vale más prevenir que curar."
    ],
    "chat": [
      "El chat del staff",
      "No es solo para leer: cada respuesta cambia algo en la sala (un speaker que no se pierde, un voluntario en el check-in, más café). Responde con Q o E, o toca, antes de que se agote la barra: si pasas, decide el azar."
    ],
    "murphy": [
      "¡Murphy!",
      "El duendecillo del caos va a sabotear algo. Tócalo y atrápalo antes de que llegue: huirá y sumarás puntos."
    ],
    "panic": [
      "¡CAOS!",
      "Cuatro marrones a la vez. Respira: primero el del anillo más vacío, luego el resto. Los voluntarios ayudan."
    ],
    "firedrill": [
      "Simulacro de incendio",
      "Todos fuera unos segundos y charlas pausadas. Toca esperar (y pedir las fechas de simulacro a la sala la próxima vez)."
    ],
    "goalOk": [
      "¡Objetivo cumplido!",
      "{goal}: la estrella es tuya. Tienes los demás arriba."
    ],
    "goalFail": [
      "Objetivo fallido",
      "{goal}: hoy no ha podido ser. Aún puedes rascar las otras estrellas."
    ],
    "burnout": [
      "Burnout",
      "Te has quedado sin energía y has petado. Tómate un café antes de llegar a cero: la barra está arriba a la derecha."
    ],
    "energy": [
      "Baja energía",
      "Organizar cansa. Pásate por el café (centro del lobby) o por la sala de speakers para recargar antes del burnout."
    ],
    "vols": [
      "Voluntarios",
      "En su puesto atienden a la gente: café, dudas, bienvenida, y la valoración sube. Toca a un voluntario y luego un problema o un puesto (círculos verdes) para moverlo."
    ],
    "rush": [
      "Hora punta",
      "Varios problemas a la vez, marcados con ⚡. Arréglalos todos antes de que uno empeore y caiga la puntuación. Repartíos el trabajo: manda al co-org y a los voluntarios."
    ],
    "ability": [
      "Tu habilidad: {name}",
      "El botón amarillo arriba (F en el teclado): {what} Luego se recarga, así que úsala cuando cuente."
    ],
    "mate": [
      "Tu co-organizador",
      "Va por libre, pero acepta órdenes: tócalo, luego toca un problema y va volando. Tú ocúpate de otra cosa."
    ],
    "waiting": [
      "La charla no empieza",
      "Hacen falta el speaker en el escenario y un proyector operativo. Cada minuto de espera resta valoración; a los 26 min, se cancela."
    ],
    "night": [
      "De madrugada",
      "De 1 a 6 de la mañana la energía vuela. Haced turnos para el café o id a la sala de descanso, si la preparasteis."
    ],
    "locked": [
      "Puerta cerrada",
      "Nadie avisó a conserjería: la gente espera fuera hasta que abran. Para la próxima, la tarjeta de llaves en el Countdown."
    ],
    "ev:meetup": [
      "Meetup de jueves",
      "Una sala, dos charlas, cuarenta pizzas. El nivel más chill: prueba los controles a tu ritmo."
    ],
    "ev:studyjam": [
      "El Study Jam",
      "Codelab en el Lab: regletas, Wi-Fi y créditos de Cloud son tu día a día. Dos salas abiertas."
    ],
    "ev:wtm": [
      "Women Techmakers",
      "Hoy la acogida lo es todo: peques despistados, permiso para fotos, accesibilidad. No dejamos a nadie atrás."
    ],
    "ev:ioext": [
      "Google I/O Extended",
      "Keynote en directo, sala a reventar y llega una persona VIP. La noche del streaming."
    ],
    "ev:hack": [
      "Hackatón nocturna",
      "De 18:00 a 10:00. Equipos atascados (🧩) esperando mentores, pizza a medianoche y demos a las 8:00."
    ],
    "ev:devfest": [
      "El DevFest",
      "Tres salas, quince sesiones y Murphy. Todo lo aprendido, a la vez."
    ],
    "tPrepWeeks": [
      "El Countdown",
      "Faltan pocas semanas: cada ronda es parte de la preparación. Tus decisiones marcan cómo empieza el gran día."
    ],
    "tPrepPips": [
      "Tus tardes libres",
      "Cada punto es una tarde. Las opciones cuestan de 0 a 2 puntos: no puedes llegar a todo."
    ],
    "tPrepOpt": [
      "Elige",
      "Toca una opción para encargarte de ella. Las etiquetas verdes y rojas te muestran qué cambia."
    ],
    "tPrepIgnore": [
      "Si pasas del tema",
      "Lo que no elijas ocurrirá igualmente: esto es lo que pasa. A veces pasar es la decisión correcta."
    ],
    "tPrepMeters": [
      "Las cuentas del chapter",
      "Presupuesto, RSVPs, comunidad, partners y energía: mira cómo oscilan."
    ],
    "tPrepClose": [
      "Cierra la ronda",
      "Cuando decidas, cierra: verás cómo ha ido la cosa y qué has aprendido."
    ],
    "tLoStats": [
      "La víspera",
      "Esto es lo que tienes para el evento: aforo previsto, voluntarios, energía y presupuesto."
    ],
    "tLoGoals": [
      "Los objetivos",
      "Tres objetivos, tres estrellas. Los verás arriba durante el evento."
    ],
    "tLoGo": [
      "¡Abrimos puertas!",
      "Cuando estés listo, abre las puertas. El juego se pausará para explicarte las novedades."
    ],
    "tSeasonEv": [
      "La temporada",
      "Seis eventos, de meetup a DevFest. Cada uno tiene tres objetivos: una estrella desbloquea el siguiente."
    ],
    "tSeasonKit": [
      "El kit del chapter",
      "Las estrellas se canjean aquí por mejoras útiles en todos los eventos."
    ],
    "p": {
      "queue": "Cola en la entrada. Toca el mostrador de check-in y quédate hasta despejarla, o manda a un voluntario.",
      "stampante": "Se atascó la impresora de acreditaciones: el check-in se ralentiza. Ve al mostrador y arréglala.",
      "speaker": "El ponente se ha perdido en el vestíbulo. Ve a por él: te seguirá. Llévalo al escenario (círculo verde).",
      "hdmi": "El portátil del ponente no conecta. Con adaptadores de la caja es un segundo; si no, toca improvisar.",
      "mic": "El micro se queda sin pilas. Coge repuestos de la caja y ve al escenario.",
      "wifi": "Se cayó el Wi-Fi: reinicia el rack en control o activa la zona Wi-Fi en el Lab.",
      "prese": "Faltan enchufes en el Lab. Las regletas están en la caja.",
      "coffee": "Se acaba el café. Rellena las cafeteras en el puesto de café.",
      "pizza": "El repartidor está en la entrada con las pizzas. Cógelas antes de que se enfríen.",
      "overflow": "Sala llena y gente fuera. Ve a la puerta: mándalos a ver el streaming en el vestíbulo.",
      "sponsor": "El patrocinador quiere hablar contigo ya. Ve a su stand.",
      "perso": "Alguien no encuentra su sala. Respóndele rápido y se irá feliz.",
      "coc": "Aviso del CoC. Va antes que nada: ve ya, escucha y protege.",
      "cancel": "El ponente no viene. En el escenario puedes improvisar (lightning talks, Q&A): actúa allí.",
      "tavoli": "Hay que preparar el Lab para el próximo taller: hace falta una persona más.",
      "overrun": "El ponente se pasa de tiempo. Al escenario: saca el cartel de «5 minutos».",
      "vip": "Una visita VIP en la entrada. Dale la bienvenida antes de que se sienta ignorada.",
      "dog": "¡Un perro en la sala! Acércate: te seguirá. Llévalo a la salida.",
      "press": "La prensa pide una entrevista: buena oportunidad para ganar puntos.",
      "flame": "Tabuladores contra espacios: segunda parte. Sepáralos antes de que vaya a más.",
      "blackout": "Corte de luz en una sala: reengancha los plomos en la sala de control.",
      "quota": "Créditos Cloud agotados en el codelab. Si tienes en la caja, se arregla al instante.",
      "stream": "El streaming no tiene audio: arregla el sonido en la mesa de control.",
      "badge": "Sin acreditaciones en el check-in. Usa las de la caja o escríbelas a mano.",
      "kid": "Un niño se ha despistado de la zona infantil. Ve con calma y acompáñalo de vuelta.",
      "access": "Ascensor averiado: acompaña al asistente al aula magna por la ruta accesible.",
      "foto": "Hacen fotos a quien no quiere salir. Ve a hablar con el fotógrafo: el consentimiento importa.",
      "mentor": "Equipo bloqueado (build en rojo, API caída). Un mentor los desbloquea: Tech irá el doble de rápido.",
      "noise": "Los vecinos se quejan del ruido. Ve a la entrada a calmar los ánimos."
    }
  },
  "perks": {
    "walkie": {
      "name": "Walkie-talkies",
      "desc": "El chat del staff espera un 50% más."
    },
    "qr": {
      "name": "Lector QR",
      "desc": "Check-in rápido en cada evento."
    },
    "kit": {
      "name": "Kit AV",
      "desc": "Adaptadores y pilas siempre en la caja."
    },
    "signs": {
      "name": "Carteles reutilizables",
      "desc": "Menos gente perdida, menos dudas por el pasillo."
    },
    "moka": {
      "name": "Cafetera moka gigante",
      "desc": "Más café en cada evento."
    },
    "shoes": {
      "name": "Zapatillas cómodas",
      "desc": "Caminas un 12% más rápido."
    },
    "squad": {
      "name": "Equipo veterano",
      "desc": "Un voluntario más en cada evento."
    },
    "colead": {
      "name": "Coorganizador",
      "desc": "¿Juegas en solitario? Alguien vendrá a echarte un cable."
    }
  },
  "help": {
    "title": "Cómo jugar",
    "steps": [
      [
        "🃏",
        "Prepara",
        "Pocas tardes libres, demasiado por hacer. Lo que nadie asume ocurre igual."
      ],
      [
        "🏃",
        "Sobrevive",
        "Toca un problema: vas y lo resuelves. El triángulo amarillo se previene, las horas punta ⚡ se superan. Tres metas, tres estrellas."
      ],
      [
        "👉",
        "Delega",
        "Toca al co-org o a un voluntario, luego el problema: van ellos. En su puesto, un voluntario da café, respuestas y bienvenida."
      ],
      [
        "💬",
        "Responde",
        "El chat del staff nunca duerme: toca una respuesta."
      ],
      [
        "📰",
        "Reflexiona",
        "La retro: qué pasó, qué te llevas."
      ]
    ],
    "keys": "Teclado: WASD/flechas + Espacio · 1-4 herramientas · Q/E respuestas · F habilidad · P pausa · M sonido",
    "table": "Los problemas"
  },
  "venues": {
    "uni": {
      "name": "Universidad",
      "desc": "Tres salas y mucho espacio. El Wi-Fi es el que es."
    },
    "cowork": {
      "name": "Coworking",
      "desc": "Wi-Fi genial y cocina de verdad; salas pequeñas, ojo a los asientos.",
      "open": "¡Puertas abiertas! Recepción abajo al centro, la caja del GDG en la oficina (abajo a la izquierda).",
      "rooms": {
        "A": "Phone booth",
        "B": "Sala de eventos",
        "L": "Sala de reuniones",
        "H": "Open space",
        "R": "Oficina",
        "S": "Lounge",
        "E": "Cocina",
        "K": "Recepción"
      }
    }
  },
  "medals": {
    "chat0": [
      "Chat limpia",
      "ningún mensaje ignorado, al menos tres respuestas"
    ],
    "speakers": [
      "Nadie se pierde",
      "ninguna charla saltada y ningún speaker perdido"
    ],
    "onTime": [
      "Reloj suizo",
      "todas las charlas a tiempo"
    ],
    "rushAll": [
      "Hora punta",
      "todas las horas punta superadas (al menos dos)"
    ],
    "prevent": [
      "Vidente",
      "cinco marrones pillados a tiempo"
    ],
    "murphy": [
      "Caza-Murphy",
      "Murphy pillado dos veces en un día"
    ],
    "team": [
      "Capitán de equipo",
      "ocho tareas dadas a co-orgs y voluntarios"
    ],
    "ability": [
      "As en la manga",
      "cuatro habilidades usadas en un día"
    ],
    "noBurnout": [
      "Zen",
      "una hackathon o DevFest sin burnout"
    ],
    "devfest3": [
      "DevFest perfecto",
      "tres estrellas en el DevFest"
    ],
    "soldout3": [
      "Aforo completo",
      "tres estrellas en sold-out"
    ],
    "weekly": [
      "Semanal",
      "un desafío semanal jugado"
    ],
    "season": [
      "Temporada completa",
      "al menos una estrella en cada evento"
    ]
  },
  "abilities": {
    "lead": [
      "Megáfono",
      "un aviso en la sala: el check-in va volando y nadie te para un rato."
    ],
    "tech": [
      "Hotfix",
      "arregla al instante el fallo técnico más urgente, esté donde esté."
    ],
    "host": [
      "Rellena el hueco",
      "durante un rato, los retrasos en las salas no bajan la valoración."
    ],
    "care": [
      "Respiro",
      "+25 de energía a quien esté cerca y calma las guerras de flameo."
    ]
  },
  "about": {
    "title": "El proyecto",
    "p1": "Quien organiza eventos tech aprende lo mismo a golpes: el portátil sin USB-C, el patrocinador que se esfuma, la mitad que no aparece. Overbooked! lo convierte en un juego cooperativo, con retro guiada al final.",
    "p2": "Situaciones y consejos basados en experiencias reales: cada tip cita su fuente. Con Gemini, el juego crea cartas, chats y periódicos a medida para tu comunidad.",
    "p3": "Nacido tras años de eventos en la comunidad Google Developer Groups, siguiendo los pasos de Last Mile Hero.",
    "credits": "Un proyecto de {author}, organizer de GDG.",
    "find": "Encuentra un GDG cerca de ti",
    "sources": "Fuentes"
  }
};
