/* French: generated by tools/translate.mjs from the English pack (gemini-3.8-flash). Edit freely. */
"use strict";
DF.L = DF.L || {};
DF.L.fr = {
  "brand": {
    "tagline": "Survis au DevFest",
    "sub": "Le jeu coop pour ceux qui organisent des événements tech",
    "by": "{chapter} présente",
    "byAny": "Ta communauté présente",
    "disclaimer": "Un projet communautaire, pas un produit Google officiel."
  },
  "ui": {
    "title": {
      "play": "Lancer la saison",
      "playSub": "6 événements, du meetup au DevFest",
      "quick": "Partie rapide",
      "quickSub": "Choisis un événement et c'est parti",
      "forge": "La crise de ton chapter",
      "forgeSub": "Transforme un vrai problème en carte",
      "help": "Comment jouer",
      "about": "Le projet",
      "record": "Record : {fb}/5 · {score} points",
      "noRecord": "Aucun événement organisé. Pour l'instant.",
      "aiOn": "Gemini activé",
      "aiOff": "Contenu hors ligne",
      "marquee": [
        "SPEAKER PORTÉ DISPARU",
        "WI-FI EN PANNE",
        "PLUS DE CAFÉ",
        "SALLE COMBLE",
        "MURPHY EST LÀ",
        "PIZZAS PERDUES",
        "IMPRIMANTE À BADGES BLOQUÉE",
        "LE SPONSOR TE CHERCHE",
        "212 RSVPS, 168 PLACES"
      ],
      "notif": [
        "Le speaker cherche un adaptateur USB-C",
        "Tu as 47 messages non lus",
        "Le traiteur demande combien de pizzas",
        "Quelqu'un a vu les clés de la salle ?",
        "Le sponsor veut un logo plus grand",
        "Maman : tu as mangé ?"
      ]
    },
    "season": {
      "title": "La saison",
      "sub": "Trois objectifs par événement : une étoile débloque le suivant.",
      "locked": "D'abord : {prev}",
      "play": "Jouer",
      "best": "Record : {fb}/5",
      "rounds": "{n} tours de prépa",
      "people": "~{n} personnes",
      "minutes": "{n} min"
    },
    "setup": {
      "eyebrow": "Nouvel événement",
      "title": "Qui organise ?",
      "venue": "Lieu",
      "relax": "Mode détente",
      "relaxSub": "plus de temps pour chaque souci et pour le chat.",
      "soldout": "Complet",
      "soldoutSub": "+40 % de monde, plus d'ennuis, un rush de plus. Record séparé.",
      "soldoutLocked": "Complet : se débloque avec 3 étoiles sur cet événement.",
      "modes": {
        "solo": [
          "Solo",
          "Tu es le lead. Tu peux recruter un co-organisateur."
        ],
        "duo": [
          "À deux",
          "Un clavier : WASD+Space et flèches+Enter."
        ],
        "online": [
          "En ligne",
          "Un salon avec code, jusqu'à 4 leads."
        ]
      },
      "onlineLocal": "Sans serveur : salon entre onglets de ce navigateur.",
      "chapter": "Communauté ou chapter",
      "chapterPh": "ex. GDG Paris",
      "city": "Ville",
      "cityPh": "Ta ville",
      "player": "Joueur {n}",
      "role": "Rôle",
      "name": "Nom",
      "back": "Retour",
      "start": "Lancer les préparatifs",
      "startDay": "Ouvrir les portes",
      "code": "Code du salon",
      "join": "Rejoindre",
      "create": "Créer un salon",
      "codeLen": "Le code fait 4 caractères.",
      "notFound": "Salon {code} introuvable.",
      "noRooms": "Ce navigateur ne gère pas les salons en ligne."
    },
    "lobby": {
      "recaptcha": "Les salons en ligne sont protégés des bots par Google reCAPTCHA.",
      "terms": "Conditions",
      "eyebrow": "Salon en ligne · {via}",
      "code": "Code",
      "host": "Envoie le code aux autres leads. Quatre max.",
      "guest": "Tu y es : l'hôte lance la prépa.",
      "you": "toi",
      "other": "prêt",
      "leave": "Quitter",
      "copy": "Copier le code",
      "copied": "Copié",
      "start": "Lancer",
      "gone": "L'hôte a fermé le salon."
    },
    "prep": {
      "title": "Le Compte à rebours",
      "hint": "Chaque point est une soirée libre. Ce que personne ne gère arrive quand même.",
      "hintTeam": "Choisis qui s'en charge, puis l'option.",
      "hintOnline": "Chacun dépense ses points : parlez-en.",
      "close": "Terminer le tour",
      "next": "Suivant",
      "toDay": "La veille →",
      "ready": "Je suis prêt",
      "isReady": "Prêt ✓",
      "hostNext": "L'hôte passe au tour suivant.",
      "ignore": "Si personne ne s'en charge",
      "why": "Pourquoi ?",
      "free": "gratuit",
      "who": "✓ {name}",
      "tired": "{name} n'en peut plus ce tour-ci.",
      "discount": "−1 pour {role}",
      "ai": "✨ De ta région",
      "aiLoading": "Gemini écrit une carte pour {city}…",
      "aiLoadingAny": "Gemini prépare une carte sur mesure…",
      "results": "Le bilan",
      "done": "FAIT",
      "skipped": "IGNORÉ",
      "overtime": "Heures sup : {n} soirées en plus, −{e} énergie.",
      "rounds": {
        "1": [
          "−1 semaine"
        ],
        "2": [
          "−3 semaines",
          "−1 semaine"
        ],
        "4": [
          "−12 semaines",
          "−8 semaines",
          "−4 semaines",
          "−1 semaine"
        ]
      }
    },
    "ai": {
      "safeTitle": "Ta clé reste dans ton navigateur.",
      "safeText": "Elle ne transite par aucun de nos serveurs et n'est stockée nulle part : elle ne va que de toi à Google. Tu peux la retirer quand tu veux.",
      "stays": "Elle reste dans ce navigateur et ne va qu'à Google.",
      "statusCap": "En pause jusqu'à demain : les 150 requêtes du jour sont épuisées (pour protéger ton quota).",
      "title": "Gemini dans le jeu",
      "chipOff": "Activer Gemini",
      "chipNA": "IA non disponible",
      "intro": "Overbooked! fonctionne très bien sans IA. Avec ta clé Gemini, il ajoute du contenu personnalisé pour ton chapter :",
      "feats": [
        "une carte « de ta région » à chaque manche du Countdown",
        "le chat du staff adapté à ta ville",
        "la Gazette locale et le conseil du coach dans la rétro",
        "la forge : transformez une vraie anecdote en carte"
      ],
      "statusOff": "IA désactivée",
      "statusPaused": "Désactivée par toi",
      "statusKey": "Active avec ta clé · {model}",
      "statusServer": "Active : offerte par l'hôte du jeu · {model}",
      "unavailableShort": "Non disponible dans cette version",
      "enable": "Réactiver",
      "disable": "Désactiver l'IA",
      "yourKey": "Ta clé Gemini",
      "saved": "Clé enregistrée {key} · {where}",
      "whereDevice": "sur cet appareil",
      "whereSession": "pour cette session uniquement",
      "remove": "Supprimer la clé",
      "keyLabel": "Clé API Gemini",
      "test": "Tester et activer",
      "testing": "Vérification de la clé avec Google…",
      "ok": "C'est bon : Gemini est activé avec {model}.",
      "remember": "Mémoriser sur cet appareil",
      "rememberSub": "sinon elle disparaît dès que tu fermes l'onglet.",
      "err": {
        "format": "Ça ne ressemble pas à une clé Gemini.",
        "rejected": "Google a rejeté la clé : vérifie qu'elle est active et que ce site est autorisé.",
        "quota": "Quota dépassé pour le moment : réessaie plus tard.",
        "models": "La clé fonctionne mais ne voit pas les modèles Gemini Flash.",
        "network": "Google ne répond pas : vérifie ta connexion et réessaie.",
        "http": "Un problème est survenu : réessaie."
      },
      "howTitle": "Comment en obtenir une en sécurité (2 min)",
      "how": [
        "Crée une clé dédiée au jeu dans Google AI Studio.",
        "Dans la console Google Cloud, restreins-la : uniquement « Generative Language API » et ce site en référent.",
        "Définis un petit budget sur le projet : en Europe, les apps utilisent l'offre payante, et une partie ne coûte que quelques centimes."
      ],
      "linkStudio": "Google AI Studio",
      "linkConsole": "Identifiants Google Cloud",
      "linkBilling": "Facturation Gemini",
      "privacy": "La clé reste dans ton navigateur et ne va qu'à Google : elle ne transite jamais par nos serveurs et nous ne la conservons pas. Avec l'IA active, Gemini reçoit le nom du chapter, la ville, les stats du jour et les histoires que tu écris dans la forge.",
      "unavailable": "L'IA n'est pas disponible dans cette version : la page ne peut pas se connecter à Google. Joue depuis le site officiel pour utiliser ta clé."
    },
    "acct": {
      "eyebrow": "Compte",
      "chip": "Connexion",
      "title": "La connexion est facultative",
      "freeTitle": "Tu peux jouer sans compte",
      "freeText": "Étoiles, kit et cartes restent sur cet appareil. Le compte sert juste à les retrouver ailleurs et à hisser ton chapter au classement.",
      "feats": [
        "Retrouve tes étoiles, kit et cartes forgées sur mobile et ordi.",
        "Place ton chapter dans le classement de la saison.",
        "Pas de newsletter, sauf si tu la demandes."
      ],
      "signIn": "Se connecter avec Google",
      "loading": "Connexion en cours…",
      "privacyNote": "On ne garde que le nécessaire pour synchroniser, et tu peux tout supprimer quand tu veux.",
      "unavailable": "Connexion possible uniquement sur le site du jeu. Ici, étoiles et cartes restent dans ce navigateur.",
      "hello": "Salut, {name} !",
      "as": "Connecté avec {email}. Tu es le seul à le voir.",
      "signOut": "Déconnexion",
      "syncing": "Synchronisation…",
      "synced": "Progression enregistrée à {time}",
      "syncErr": "Impossible de sauvegarder en ligne : nouvel essai à la prochaine modif.",
      "boardTitle": "Ton chapter au classement",
      "boardOn": "Mettre mon chapter au classement",
      "boardOnSub": "Tes étoiles de la saison comptent ({n} ⭐). Le classement affiche le nom du chapter, jamais le tien.",
      "boardLive": "{chapter} est au classement : actualisation toutes les quelques minutes.",
      "boardPending": "Les noms commençant par GDG, GDSC ou WTM s'affichent direct ; les autres après vérif.",
      "boardNoName": "Tape le nom de ton chapter (2 à 40 caractères).",
      "contactTitle": "Contact",
      "consent": "Vous pouvez m'écrire pour les nouveautés du jeu.",
      "consentSub": "Facultatif. Ton e-mail sert uniquement pour OVERBOOKED! et seulement si coché. Décoche quand tu veux.",
      "deleteTitle": "Supprimer le compte",
      "deleteText": "Supprime le compte et tout ce qui est en ligne. Le jeu sur cet appareil reste intact.",
      "delete": "Supprimer le compte",
      "deleteSure": "Tu confirmes ? Le compte et tes données en ligne disparaissent à jamais, classement compris.",
      "deleteYes": "Oui, supprimer",
      "deleteNo": "Annuler",
      "reauth": "Par sécurité, Google veut vérifier que c'est bien toi. Ensuite, adieu le compte.",
      "reauthBtn": "Confirmer avec Google et supprimer",
      "deleted": "Compte supprimé. Tes données en ligne ont disparu.",
      "err": {
        "popup": "Ton navigateur a bloqué la fenêtre Google : réessaie ou autorise les pop-ups ici.",
        "disabled": "La connexion Google n'est pas encore activée. Réessaie bientôt.",
        "domain": "Impossible de se connecter depuis cette adresse.",
        "network": "Problème réseau : réessaie.",
        "check": "Échec du test anti-robot : recharge la page et réessaie.",
        "denied": "Action non autorisée.",
        "load": "Impossible de charger la connexion : vérifie ton réseau.",
        "generic": "Un truc a coincé : réessaie."
      }
    },
    "board": {
      "short": "Classement",
      "eyebrow": "La saison des chapters",
      "title": "Classement des chapters",
      "intro": "Les étoiles de la saison cumulées par chapter. Chaque joueur vaut max 18 étoiles : pour grimper, ramène ton équipe.",
      "loading": "Chargement du classement…",
      "empty": "Aucun chapter pour l'instant : la 1re place est à prendre.",
      "error": "Impossible de charger le classement : réessaie plus tard.",
      "unavailable": "Le classement est dispo uniquement sur le site du jeu.",
      "meta": "{chapters} chapters · {players} joueurs · màj toutes les quelques minutes",
      "join": "Ajoute ton chapter",
      "mine": "Mon chapter"
    },
    "privacy": {
      "link": "Confidentialité",
      "eyebrow": "Confidentialité",
      "title": "La confidentialité, en clair",
      "intro": "Zéro cookie, zéro pub, aucun pistage intersite. Voici ce qui arrive sur nos serveurs, et pourquoi.",
      "statsTitle": "Stats anonymes",
      "statsText": "Pour savoir si le jeu aide les communautés, on compte les visites et les journées jouées. Chaque décompte contient peu de données : langue, provenance (LinkedIn, Medium…), mobile ou ordi, fuseau horaire, événement, étoiles, IA activée ou non, et le nom du chapter s'il commence par GDG, GDSC ou WTM. Aucun identifiant ni adresse IP : le serveur ajoute juste 1 à des totaux.",
      "playTitle": "Journal des parties",
      "playText": "Pour améliorer le jeu, on garde un résumé anonyme de chaque journée : objectifs, pépins ratés, réponses dans le chat, choix du Countdown, temps de jeu, abandons en cours de route et erreurs du jeu. Juste la date, aucun identifiant, jamais de marketing. Supprimé automatiquement au bout de 12 mois.",
      "logsTitle": "Logs techniques",
      "logsText": "Comme tout site, les logs de Google Cloud gardent l'adresse IP, le navigateur et la page de chaque requête pendant 30 jours. Utilisés uniquement pour la sécurité et le débogage, jamais pour compter ou profiler les joueurs.",
      "statsOn": "Contribuer aux stats anonymes",
      "statsOnSub": "Inclut aussi le journal des parties. Désactivable à tout moment : le jeu marche pareil.",
      "statsDnt": "Ton navigateur demande à ne pas être pisté : aucune stat envoyée.",
      "statsOff": "Les stats sont désactivées dans cette version du jeu.",
      "acctTitle": "Compte Google (facultatif)",
      "acctText": "Si tu te connectes avec Google, on conserve ton identifiant, nom et e-mail (gérés par Firebase Authentication), tes étoiles, ton kit, tes cartes forgées et le nom de ton chapter. Ça synchronise tes appareils et alimente le classement si tu le souhaites (seul le chapter y apparaît). On ne t'écrit qu'avec ton accord. Tout reste jusqu'à ce que tu supprimes ton compte depuis l'écran Compte.",
      "roomsTitle": "Salons en ligne",
      "roomsText": "Les salons utilisent une connexion anonyme temporaire et Google reCAPTCHA pour bloquer les bots. Les données de la partie disparaissent quand l'hôte ferme le salon ; les connexions anonymes s'effacent après 30 jours.",
      "aiTitle": "Gemini",
      "aiText": "Si tu actives l'IA, ta clé reste dans ton navigateur et ne va que chez Google : elle ne transite jamais par nos serveurs.",
      "whoTitle": "Qui nous sommes, qui nous aide",
      "whoText": "OVERBOOKED! est un projet communautaire créé par Nicola Guglielmi (GDE). Le jeu utilise Google Firebase (Hosting, Authentication, Cloud Functions et Realtime Database, avec données de jeu et compteurs hébergés en Belgique) et les polices de Google Fonts.",
      "contact": "Questions ou demandes concernant tes données :",
      "updated": "Dernière mise à jour : {date}"
    },
    "coach": {
      "ok": "Compris",
      "next": "Suivant",
      "done": "Terminé",
      "off": "Plus de conseils",
      "more": "+{n}",
      "again": "Revoir les conseils",
      "reset": "Conseils réactivés"
    },
    "goals": {
      "rating": "Note d'au moins {min}",
      "onTime": "Chaque talk à l'heure",
      "noCancel": "Aucun talk annulé",
      "pizza": "Les pizzas arrivent chaudes",
      "lab": "Le Lab tourne sans accroc",
      "chat": "Répondre à {n} messages",
      "care": "Personne n'est laissé de côté",
      "coc": "Chaque signalement traité",
      "stream": "Le stream ne coupe pas",
      "vip": "Accueillir le VIP",
      "mentors": "Débloquer {n} équipes",
      "demo": "Toutes les démos projetées",
      "murphy": "Stopper Murphy"
    },
    "weekly": {
      "stub": "Défi de la semaine",
      "stubSub": "{event} : la même journée pour tous",
      "eyebrow": "Défi de la semaine · {week}",
      "rules": "Jusqu'à dimanche, la même journée pour tous : mêmes galères, mêmes heures de pointe, prépa standard, sans kit ni mode relax. Choisis ton rôle et rejoue à volonté : seul ton record compte.",
      "for": "Tu joues pour (ton chapter)",
      "play": "Jouer",
      "best": "Ton record cette semaine : {n} points",
      "noBest": "Tu n'as pas encore joué cette semaine.",
      "cup": "Chapter Cup",
      "cupNote": "Chaque chapter cumule les 3 meilleurs scores de ses joueurs. Le serveur rejoue chaque partie pour vérif. Seuls les noms commençant par GDG, GDSC ou WTM participent.",
      "cupOff": "La Chapter Cup est uniquement dispo sur le site du jeu.",
      "cupEmpty": "Aucun chapter cette semaine : la 1re place est à prendre.",
      "retro": "Défi de la semaine : {n} points",
      "sending": "Envoi et vérification…",
      "rank": "{chapter} est #{rank} de la Chapter Cup",
      "verified": "Vérifié ✓ ({n} points) · ton record : {best}",
      "notSent": "Non envoyé ({why}) : réessaie plus tard."
    },
    "medals": {
      "title": "Médailles",
      "new": "Nouvelle médaille !",
      "newMany": "Nouvelles médailles !"
    },
    "kit": {
      "title": "Le kit du chapter",
      "sub": "Chaque étoile est un outil permanent",
      "intro": "Dépense les étoiles de la saison ici : chaque amélioration sert à tous les événements, en solo ou en duo. Change-les quand tu veux.",
      "left": "étoiles dispo, sur {total} gagnées",
      "spend": "Tu as {n} étoiles à dépenser dans le kit du chapter",
      "open": "Ouvrir le kit"
    },
    "meters": {
      "budget": "Budget",
      "rsvp": "RSVP",
      "community": "Communauté",
      "partner": "Partenaires",
      "energy": "Énergie"
    },
    "streams": {
      "Sede": "Lieu",
      "Logistica": "Logistique",
      "Speaker": "Speakers",
      "Sponsor": "Sponsors",
      "Community": "Communauté",
      "Volontari": "Bénévoles",
      "Accoglienza": "Accueil",
      "Team": "Équipe"
    },
    "fx": {
      "budget": "{s}{v} €",
      "rsvp": "{s}{v} RSVP",
      "community": "{s}{v} communauté",
      "partner": "{s}{v} partenaires",
      "energy": "{s}{v} énergie",
      "vols": "+{v} bénévoles"
    },
    "set": {
      "networkCheck": "réseau vérifié",
      "sponsorPack": "pack sponsor",
      "coLead": "co-organisateur",
      "cocTeam": "contacts CoC",
      "signage": "signalétique",
      "catering": "traiteur",
      "provaTecnica": "répétition technique",
      "labReady": "Lab prêt",
      "checkinQR": "check-in QR",
      "speakerCare": "speaker care",
      "backupSpeaker": "speaker de secours",
      "lightningJolly": "joker lightning",
      "waitlist": "liste d'attente",
      "reminder": "rappels",
      "runOfShow": "déroulé staff",
      "raffle": "tirage au sort",
      "fireCheck": "pas d'alarme surprise",
      "pressReady": "presse prête",
      "coffeePlus": "plus de café",
      "dogGate": "porte surveillée",
      "venueKey": "clés en main",
      "timeKeeper": "panneau de temps",
      "streamTest": "stream testé",
      "vipReady": "accueil VIP",
      "kidsCorner": "coin enfants",
      "photoLanyards": "tours de cou photo",
      "accessRoute": "accès PMR",
      "mentors": "mentors",
      "restArea": "salle de repos",
      "judgingRules": "règlement",
      "nightGuard": "sécurité nocturne"
    },
    "lo": {
      "eyebrow": "La veille · {chapter}",
      "title": "Voilà avec quoi tu arrives",
      "people": "~{n}",
      "peopleSub": "personnes attendues ({rsvp} RSVP, {pct} %)",
      "vols": "bénévoles",
      "energy": "énergie",
      "budget": "budget",
      "sat": "satisfaction de départ",
      "staff": "Le staff",
      "box": "La boîte du GDG",
      "prep": "La préparation",
      "missing": "manquant",
      "go": "Ouvrir les portes",
      "wait": "L'hôte ouvre les portes.",
      "goals": "Objectifs du jour",
      "controls": "Touche un souci pour le régler · touche le co-org ou un bénévole, puis la tâche · clavier : WASD + Espace"
    },
    "flags": {
      "checkinQR": "Check-in QR",
      "catering": "Traiteur confirmé",
      "speakerCare": "Speaker care",
      "backupSpeaker": "Speaker de secours",
      "provaTecnica": "Répétition technique",
      "networkCheck": "Réseau vérifié",
      "labReady": "Lab prêt",
      "cocTeam": "Contacts CoC",
      "runOfShow": "Déroulé staff",
      "signage": "Signalétique",
      "raffle": "Tirage au sort final",
      "sponsorPack": "Pack sponsor",
      "fireCheck": "Pas d'alarme surprise",
      "pressReady": "Presse attendue",
      "dogGate": "Porte surveillée",
      "streamTest": "Stream testé",
      "vipReady": "Accueil VIP prévu",
      "timeKeeper": "Panneau de temps",
      "kidsCorner": "Coin enfants",
      "photoLanyards": "Tours de cou photo",
      "accessRoute": "Accès PMR",
      "mentors": "Mentors en relais",
      "restArea": "Salle de repos",
      "judgingRules": "Règlement public",
      "nightGuard": "Sécurité nocturne"
    },
    "hud": {
      "sat": "AVIS",
      "goals": "OBJECTIFS",
      "points": "POINTS",
      "combo": "COMBO ×{n}",
      "chat": "CHAT DU STAFF",
      "forced": "pause forcée",
      "box": "BOÎTE GDG",
      "boxHere": "BOÎTE · PRENDS ICI",
      "boxIn": "À LA BOÎTE ↓",
      "boxTap": "touche un outil pour le prendre",
      "boxEmpty": "c'est vide : remplis-la au Countdown",
      "missing": "manquant",
      "panic": "LE CHAOS !",
      "rush": "COUP DE FEU",
      "open": "Portes ouvertes",
      "next": "Bientôt : {t}",
      "end": "Clôture",
      "closed": "FERMÉ",
      "stage": "SCÈNE",
      "late": "{m} min de retard",
      "starting": "Ça commence…",
      "noSignal": "NO SIGNAL",
      "unread": "+{n}",
      "reply": "Répondre"
    },
    "pause": {
      "title": "En pause",
      "text": "Le DevFest peut attendre. En vrai, ce serait un luxe.",
      "resume": "Reprendre",
      "restart": "Recommencer",
      "help": "Comment jouer",
      "audioOn": "Son : oui",
      "audioOff": "Son : non",
      "menu": "Menu",
      "coachOn": "Conseils : oui",
      "coachOff": "Conseils : non"
    },
    "retro": {
      "goalOk": "FAIT",
      "goalNo": "MANQUÉ",
      "paper": "La Gazette du DevFest",
      "feedback": "Avis {fb}/5",
      "points": "{n} points",
      "record": "nouveau record !",
      "menu": "Menu",
      "again": "Rejouer",
      "next": "Événement suivant",
      "season": "Saison",
      "leave": "Quitter la salle",
      "present": "participants",
      "onTime": "sessions à l'heure",
      "fixed": "résolus",
      "prevented": "évités à temps",
      "escaped": "échappés",
      "queue": "max en file",
      "chat": "chats gérés",
      "rush": "coups de feu",
      "feel": "C'était comment ?",
      "feels": [
        "Épuisé",
        "Fier",
        "Chaotique",
        "Fun",
        "Serein",
        "On remet ça !"
      ],
      "moments": "Moments clés",
      "quiet": "Journée calme. Suspect.",
      "lessons": "À retenir",
      "coach": "Le coach",
      "group": "Pour la rétro d'équipe",
      "commit": "Mon engagement",
      "commitPh": "Un truc concret",
      "copy": "Copier pour le chat des leads",
      "copied": "Copié",
      "aiWriting": "Gemini rédige la Gazette…",
      "unlocked": "Débloqué : {ev}",
      "share": "🎟️ Overbooked! · {ev} {chapter}\n{stars} avis {fb}/5 · {present} participants · {ontime} à l'heure",
      "shareFeel": "Ressenti : {feel}",
      "shareLesson": "Leçon : {lesson}",
      "shareCommit": "Mon engagement : {commit}"
    },
    "forge": {
      "title": "La crise de ton chapter",
      "intro": "Raconte une galère vécue. Elle devient une carte de ton Countdown, à échanger avec d'autres leads.",
      "story": "Qu'est-ce qui s'est passé ?",
      "storyPh": "La veille, ils nous ont piqué la salle pour la conf du doyen…",
      "ai": "✨ Créer la carte avec Gemini",
      "aiWorking": "Gemini rédige…",
      "aiFail": "Gemini ne répond pas : remplis-la à la main.",
      "aiOff": "Gemini n'est pas dispo ici : remplis-la à la main.",
      "manual": "Ou écris-la toi-même",
      "ctitle": "Titre",
      "ctext": "Situation",
      "stream": "Pôle",
      "round": "Quand",
      "o": "Option {n}",
      "cost": "Soirées",
      "effect": "Effet",
      "cignore": "Si personne ne gère",
      "tip": "La leçon retenue",
      "save": "Ajouter à mon deck",
      "mine": "Ton deck ({n})",
      "empty": "Pas encore de carte.",
      "copy": "Copier",
      "copied": "Copié",
      "del": "Supprimer",
      "import": "Importer la carte d'un autre chapter",
      "importPh": "Colle le texte copié ici",
      "importBtn": "Importer",
      "importErr": "Ce n'est pas une carte Overbooked!."
    },
    "common": {
      "back": "Retour",
      "close": "Fermer",
      "ok": "Compris",
      "loading": "…"
    }
  },
  "roles": {
    "lead": {
      "name": "Lead",
      "blurb": "Gens et décisions : sponsors, VIP, salles pleines, Code of Conduct."
    },
    "tech": {
      "name": "Tech",
      "blurb": "Projecteurs, micros, réseau, courant. Porte deux outils."
    },
    "host": {
      "name": "Accueil",
      "blurb": "Check-in, café, déj, badges. Et les chiens."
    },
    "care": {
      "name": "Speaker care",
      "blurb": "Speakers perdus, talks qui débordent, scènes."
    }
  },
  "tools": {
    "adattatori": {
      "name": "Adaptateurs",
      "hint": "HDMI, USB-C, DisplayPort"
    },
    "batterie": {
      "name": "Piles",
      "hint": "pour les micros sans fil"
    },
    "ciabatte": {
      "name": "Multiprises",
      "hint": "prises pour le Lab"
    },
    "hotspot": {
      "name": "Hotspot",
      "hint": "réseau de secours"
    },
    "badge": {
      "name": "Badges en rab",
      "hint": "pour les non-inscrits"
    },
    "crediti": {
      "name": "Crédits Cloud",
      "hint": "clés API de secours"
    }
  },
  "rooms": {
    "A": "Grand amphi",
    "B": "Salle B",
    "L": "Lab",
    "H": "Hall",
    "R": "Régie",
    "S": "Espace speakers",
    "E": "Expo",
    "K": "Check-in"
  },
  "posts": {
    "checkin": "Check-in",
    "coffee": "Café",
    "info": "Point info",
    "stageA": "Grand amphi",
    "stageB": "Salle B",
    "lab": "Lab",
    "entrance": "Entrée",
    "sponsor1": "Expo",
    "kids": "Coin enfants",
    "tableA": "Tables"
  },
  "stations": {
    "stageA": "la scène de l'amphi",
    "stageB": "la scène de la salle B",
    "lab": "le Lab",
    "coffee": "le café",
    "router": "la baie de brassage",
    "checkin": "le check-in",
    "entrance": "l'entrée",
    "box": "la boîte GDG",
    "info": "le stand info",
    "sponsor1": "le stand sponsor",
    "sponsor2": "le stand sponsor",
    "hall": "le hall",
    "expo": "l'espace expo",
    "green": "la salle des speakers",
    "doorA": "la porte de l'amphi",
    "doorB": "la porte de la salle B",
    "phone": "le téléphone",
    "kids": "le coin enfants",
    "tableA": "les tables de l'amphi",
    "tableL": "les tables du Lab"
  },
  "problems": {
    "kid": {
      "name": "Enfant perdu",
      "how": "Ramène-le à l'espace enfants."
    },
    "access": {
      "name": "Accès PMR",
      "how": "Accompagne l'invité dans le Grand Amphi."
    },
    "foto": {
      "name": "Photo sans accord",
      "how": "Va parler au photographe."
    },
    "mentor": {
      "name": "Équipe bloquée",
      "how": "Un mentor à la table."
    },
    "noise": {
      "name": "Voisins en colère",
      "how": "Calme-les à l'entrée."
    },
    "queue": {
      "name": "File au check-in",
      "how": "Maintiens enfoncé au comptoir."
    },
    "stampante": {
      "name": "Imprimante de badges bloquée",
      "how": "Maintiens enfoncé au check-in."
    },
    "speaker": {
      "name": "Speaker introuvable",
      "how": "Retrouve-le et mène-le sur scène."
    },
    "hdmi": {
      "name": "Pas de signal",
      "how": "Adaptateurs, puis maintiens sur scène."
    },
    "mic": {
      "name": "Micro à plat",
      "how": "Piles, puis maintiens enfoncé."
    },
    "wifi": {
      "name": "Wi-Fi en panne",
      "how": "Redémarre la baie en régie, ou hotspot au Lab."
    },
    "prese": {
      "name": "Plus de prises",
      "how": "Multiprises dans le Lab."
    },
    "coffee": {
      "name": "Plus de café",
      "how": "Maintiens enfoncé au stand café."
    },
    "pizza": {
      "name": "Livreur perdu",
      "how": "File à l'entrée."
    },
    "overflow": {
      "name": "Salle comble",
      "how": "Maintiens à la porte : stream dans le hall."
    },
    "sponsor": {
      "name": "Le sponsor te demande",
      "how": "Passe à leur stand."
    },
    "perso": {
      "name": "Participant perdu",
      "how": "Deux secondes pour l'aiguiller."
    },
    "coc": {
      "name": "Signalement CoC",
      "how": "Staff uniquement, tout de suite, au calme."
    },
    "cancel": {
      "name": "Désistement speaker",
      "how": "Improvise toi-même sur scène."
    },
    "tavoli": {
      "name": "Lab à réagencer",
      "how": "Besoin de deux personnes."
    },
    "overrun": {
      "name": "Le speaker dépasse",
      "how": "Pancarte « 5 minutes » depuis la scène."
    },
    "vip": {
      "name": "Visite surprise",
      "how": "Le lead l'accueille à l'entrée."
    },
    "dog": {
      "name": "Un chien dans la salle !",
      "how": "Attrape-le et sors-le."
    },
    "press": {
      "name": "Presse locale",
      "how": "Interview à l'espace expo : une opportunité !"
    },
    "flame": {
      "name": "Tabs ou espaces ?",
      "how": "Sépare la bagarre."
    },
    "blackout": {
      "name": "Panne de courant",
      "how": "Réarme le disjoncteur en régie."
    },
    "quota": {
      "name": "Quota d'API dépassé",
      "how": "Crédits Cloud dans le Lab."
    },
    "stream": {
      "name": "Stream muet",
      "how": "Règle le son en régie."
    },
    "badge": {
      "name": "Plus de badges",
      "how": "Badges de secours au check-in."
    }
  },
  "hints": {
    "kid": "🧸 Enfant perdu : rejoins-le, il te suit jusqu'au coin enfants.",
    "access": "♿ Rejoins l'invitée à l'entrée et guide-la vers la Grande Salle.",
    "mentor": "🧩 Équipe bloquée : touche-la, le Tech va deux fois plus vite.",
    "hdmi": "📽️ Ordi muet ? Adaptateurs dans la boîte GDG (régie), puis maintiens sur scène.",
    "queue": "🧾 File d'attente ! Maintiens à l'enregistrement. Les bénévoles là-bas gèrent en solo.",
    "tavoli": "🪑 Le Lab se bouge à deux : touche un bénévole, puis le Lab.",
    "wifi": "📡 Wi-Fi en panne : redémarre la baie en régie, ou hotspot au Lab.",
    "coc": "🛡️ Signalement CoC : priorité absolue. Vas-y immédiatement.",
    "speaker": "🧭 Speaker égaré : rejoins-le, il te suit jusqu'à la scène.",
    "dog": "🐕 Un chien ! Rejoins-le : il te suit jusqu'à la sortie.",
    "press": "🎙️ Opportunité : l'interview booste la note globale.",
    "overrun": "⏰ Ça déborde : maintiens sur scène, pancarte « 5 minutes ».",
    "chat": "💬 Le chat du staff : choisis une réponse. Ignorer coûte cher."
  },
  "events": {
    "wtm": {
      "name": "Women Techmakers IWD",
      "when": "Samedi après-midi",
      "blurb": "Talks, panels et mentorat. L'accueil avant tout."
    },
    "hack": {
      "name": "Hackathon nocturne",
      "when": "Samedi soir",
      "blurb": "Seize heures, trente équipes, pizza à minuit."
    },
    "meetup": {
      "name": "Meetup du jeudi",
      "when": "Jeudi, 18h30",
      "blurb": "Deux talks, une salle, quarante pizzas."
    },
    "studyjam": {
      "name": "Build with AI Study Jam",
      "when": "Samedi matin",
      "blurb": "Codelab dans le Lab. Le Wi-Fi est une légende."
    },
    "ioext": {
      "name": "Google I/O Extended",
      "when": "Vendredi soir",
      "blurb": "Keynote en direct, salle comble, VIP en approche."
    },
    "devfest": {
      "name": "DevFest",
      "when": "Samedi, toute la journée",
      "blurb": "Trois salles, quinze sessions, Murphy."
    }
  },
  "breaks": {
    "coffee": "Pause café",
    "lunch": "Déjeuner",
    "pizza": "Pizza & networking",
    "dinner": "Dîner buffet",
    "midnight": "Pizza de minuit",
    "coffee4": "Café de 4h",
    "breakfast": "Petit-déj"
  },
  "talks": {
    "wtmKeynote": "Keynote : la tech qu'on bâtit ensemble",
    "wtmCareer": "Parcours non linéaires dans la tech",
    "wtmAI": "IA responsable, en pratique",
    "wtmPanel": "Table ronde : leadership et communauté",
    "wtmMentoring": "Cercles de mentorat",
    "wtmLeadership": "De dev à tech lead",
    "wtmPhoto": "Networking et photo de groupe",
    "hkKickoff": "Lancement : règles et équipes",
    "hkHackA": "Ça hacke dans le Grand Amphi",
    "hkHackL": "Ça hacke dans le Lab",
    "hkMentors": "Permanence des mentors",
    "hkLate": "Le talk d'1h : debug à minuit",
    "hkDemo": "Démos des équipes",
    "hkAwards": "Remise des prix",
    "meetupAI": "Gemini dans ton éditeur",
    "meetupFlutter": "Une app Flutter en 40 minutes",
    "sjIntro": "Build with AI : c'est parti !",
    "sjLab1": "Codelab : ton premier agent",
    "sjPrompt": "Le prompt pour les allergiques aux prompts",
    "sjLab2": "Codelab : Gemini dans le navigateur",
    "sjGemma": "Gemma sur ton téléphone",
    "ioKeynote": "Keynote Google I/O en direct",
    "ioAndroid": "Les nouveautés d'Android",
    "ioWeb": "Web : ce qu'on peut utiliser dès aujourd'hui",
    "ioGemini": "Gemini : ce qui change pour nous",
    "ioFirebase": "Firebase en une heure",
    "dfKeynote": "Keynote : la communauté à l'ère des agents",
    "dfAdk": "Des agents avec ADK, du notebook à Cloud Run",
    "dfFlutter": "Flutter : une codebase, six plateformes",
    "dfCodelab": "Codelab : Build with AI",
    "dfGemini": "Gemini en prod sans cramer le budget",
    "dfA11y": "Accessibilité : ton site n'est pas fini",
    "dfGemma": "Gemma sur mobile : IA on-device",
    "dfKmp": "Kotlin Multiplatform dans le monde réel",
    "dfFirebase": "Workshop : Firebase en une heure",
    "dfFrantoio": "J'ai mis de l'IA dans le moulin à huile de mon papi",
    "dfBaseline": "Web Baseline : ce qu'on peut utiliser aujourd'hui",
    "dfMonolith": "Du monolithe aux microservices (et inversement)",
    "dfPrompt": "Prompt engineering pour les allergiques aux prompts",
    "lightning": "Lightning talks de la communauté",
    "raffle": "Tirage au sort et photo de groupe"
  },
  "cards": {
    "wtm_kids": {
      "title": "Qui garde les enfants ?",
      "text": "La moitié des speakers ont des enfants en bas âge.",
      "o": [
        "Espace enfants avec nounou",
        "Les parents vont gérer"
      ],
      "ignore": "Les enfants errent sur place.",
      "tipT": "L'espace enfants élargit le public",
      "tipD": "Un coin surveillé, des jeux et une nounou : les parents de jeunes enfants peuvent enfin venir. PyCon UK le fait depuis 2016."
    },
    "wtm_photo": {
      "title": "Photos ou pas photos ?",
      "text": "Le photographe arrive à 14h.",
      "o": [
        "Tours de cou de couleur pour le consentement",
        "Un mot à l'entrée"
      ],
      "ignore": "Tout le monde est photographié.",
      "tipT": "Rouge = pas de photo, vert = ok",
      "tipD": "Les tours de cou de couleur indiquent qui refuse d'apparaître. Mozilla en use à ses events."
    },
    "wtm_access": {
      "title": "L'ascenseur du lieu",
      "text": "Il paraît qu'il se bloque parfois.",
      "o": [
        "Repérage avec une personne en fauteuil",
        "Demander les clés du monte-charge"
      ],
      "ignore": "Espérons qu'il tienne.",
      "tipT": "L'accessibilité se valide avant",
      "tipD": "Accès, ascenseurs, toilettes, scène : une visite avec ceux qui les utilisent repère tout en une heure."
    },
    "wtm_speakers": {
      "title": "Le line-up",
      "text": "Deux speakers manquent, le temps presse.",
      "o": [
        "Appel avec mentorat pour débutants",
        "Inviter des connaissances"
      ],
      "ignore": "Un programme plus court.",
      "tipT": "Les nouvelles voix se cultivent",
      "tipD": "Un appel avec mentorat fait monter sur scène des profils qui n'auraient jamais postulé. C'est l'essence de Women Techmakers."
    },
    "hk_mentors": {
      "title": "Qui aide les équipes la nuit ?",
      "text": "Trente équipes, personne d'éveillé à 3h.",
      "o": [
        "Recruter des mentors par roulement",
        "Deux-trois potes experts"
      ],
      "ignore": "Les équipes se débrouillent.",
      "tipT": "Les mentors font le hackathon",
      "tipD": "Sans mentor, une équipe bloque des heures. MLH les intègre pleinement à l'event, même la nuit."
    },
    "hk_food": {
      "title": "Y a-t-il à manger ?",
      "text": "Seize heures, quatre-vingt-dix personnes.",
      "o": [
        "Pizza à minuit et petit-déj",
        "Snacks et distributeurs"
      ],
      "ignore": "Chacun ramène son repas.",
      "tipT": "Nourriture, Wi-Fi et prises",
      "tipD": "Le trio vital pour un hackathon, selon MLH. Commande selon les effectifs confirmés."
    },
    "hk_rest": {
      "title": "Qui dort où ?",
      "text": "À 4h du mat', certains vont s'écrouler.",
      "o": [
        "Salle de repos avec lits de camp",
        "Des poufs feront l'affaire"
      ],
      "ignore": "Poufs et manteaux.",
      "tipT": "La nuit doit s'organiser",
      "tipD": "Une salle calme et des roulements de staff : s'écrouler à 4h, c'est rater la démo à 9h."
    },
    "hk_rules": {
      "title": "Règles et prix",
      "text": "Les critères du jury ne sont pas écrits.",
      "o": [
        "Critères publics dès le premier jour",
        "Le jury décide sur le vif"
      ],
      "ignore": "On verra bien à la fin.",
      "tipT": "Règles claires, verdict accepté",
      "tipD": "Des critères publics dès le coup d'envoi évitent litiges et rancœurs à la remise des prix."
    },
    "hk_night": {
      "title": "Le lieu la nuit",
      "text": "Le gardien ferme à 22h. Les voisins dorment.",
      "o": [
        "Autorisation de nuit et sécurité",
        "On croise les doigts"
      ],
      "ignore": "On croise les doigts.",
      "tipT": "Anticiper la nuitée",
      "tipD": "Un hackathon de nuit exige un lieu ouvert, de la sécurité et le respect du voisinage."
    },
    "sede": {
      "title": "Il nous faut une salle de 170 places",
      "text": "La date doit être fixée maintenant.",
      "o": [
        "Grand amphi de l'université",
        "Centre de conférences"
      ],
      "ignore": "Solution de secours bancale, réseau pourri.",
      "tipT": "Les lieux se réservent des mois à l'avance",
      "tipD": "GDG Spain a mis trois mois. La fac est un partenaire idéal, mais vérifie le réseau : 30 Mbps pour 100 personnes."
    },
    "sponsor": {
      "title": "1 500 € pour la liste d'emails",
      "text": "Un sponsor réclame les adresses des inscrits.",
      "o": [
        "Stand et logo, pas de données",
        "Prends l'argent, on en a besoin"
      ],
      "ignore": "Le sponsor va voir ailleurs.",
      "tipT": "Les données ne sont pas à vendre",
      "tipD": "Partager les emails exige leur consentement (RGPD). Offre aux sponsors de la visibilité et 5-10 min sur scène."
    },
    "team": {
      "title": "Ton bus factor est de 1",
      "text": "Si tu déménages, le chapter meurt avec toi.",
      "o": [
        "Recruter un co-organisateur",
        "Impliquer le GDG on Campus"
      ],
      "ignore": "Tout repose sur toi.",
      "tipT": "Une équipe modeste mais réelle",
      "tipD": "Un gros event tient avec 3 à 9 personnes et un lead par pôle. Tout gérer seul mène au burn-out."
    },
    "promo": {
      "title": "Les inscriptions stagnent",
      "text": "Encore huit semaines.",
      "o": [
        "Invitations : facs, meetups, chapters",
        "Post sponsorisé"
      ],
      "ignore": "Ça monte tout seul, doucement.",
      "tipT": "Trois fois avant de s'inscrire",
      "tipD": "Commence la promo deux mois avant : les gens ont besoin de voir l'événement trois fois."
    },
    "volontari": {
      "title": "Qui aide le jour J ?",
      "text": "Check-in, café, salles : on manque de bras.",
      "o": [
        "Call avec briefing de 30 min",
        "Demande à des potes"
      ],
      "ignore": "Le jour J, tu seras solo.",
      "tipT": "Mieux vaut trop que pas assez",
      "tipD": "Recrute les bénévoles un mois avant. DevFest Ukraine : 30 bénévoles pour 500 personnes."
    },
    "cfp": {
      "title": "4 propositions, toutes sur l'AI",
      "text": "Le CFP n'avance pas.",
      "o": [
        "Demande aux chapters voisins et GDEs",
        "Prolonge le CFP"
      ],
      "ignore": "Programme monotone, moins d'inscrits.",
      "tipT": "Les speakers viennent du réseau",
      "tipD": "Deux talks par mois = 24 speakers par an. Le DevFest Italia 2020 a réuni dix GDG."
    },
    "coc": {
      "title": "Le Code of Conduct suffit-il ?",
      "text": "Le lien y est. Personne ne sait gérer un signalement.",
      "o": [
        "Deux contacts formés",
        "Le lien suffit"
      ],
      "ignore": "Le lien reste là.",
      "tipT": "Un CoC est un protocole",
      "tipD": "Staff identifiable, chaque signalement écouté. PyCon 2019 en a reçu 13."
    },
    "diversita": {
      "title": "Neuf speakers, que des hommes",
      "text": "Une participante te le fait remarquer.",
      "o": [
        "Chercher des speakers variées",
        "L'année prochaine"
      ],
      "ignore": "Le lineup reste tel quel.",
      "tipT": "La diversité s'anticipe",
      "tipD": "Beaucoup de DevFest fixent des objectifs : l'Amérique du Nord 2018 visait 35 % de conférencières."
    },
    "accesso": {
      "title": "Trois marches, pas de rampe",
      "text": "Une personne en fauteuil demande si c'est accessible.",
      "o": [
        "Rampe et accès fléchés",
        "On verra le jour même"
      ],
      "ignore": "Personne ne répond.",
      "tipT": "L'accessibilité se conçoit",
      "tipD": "Entrée de plain-pied, micros en salle, espace calme : le guide SIGACCESS est une checklist."
    },
    "swag": {
      "title": "Les t-shirts arrivent lundi",
      "text": "Le DevFest a lieu samedi.",
      "o": [
        "Livraison express",
        "Tant pis, des stickers"
      ],
      "ignore": "Pas de t-shirts.",
      "tipT": "Le swag compte moins qu'on croit",
      "tipD": "Le swag coûte cher, arrive en retard et ne retient personne : un bon repas fait mieux."
    },
    "sponsorvia": {
      "title": "Le sponsor change d'avis",
      "text": "Ton contact a changé de boîte.",
      "o": [
        "Fais signer l'accord",
        "La fromagerie offre le déj"
      ],
      "ignore": "L'argent s'envole.",
      "tipT": "Contrats signés",
      "tipD": "Les sponsors disparaissent si leur contact part. Sans contrat, la conférence peut capoter."
    },
    "promotalk": {
      "title": "Un talk transformé en pub",
      "text": "Un membre veut présenter son produit.",
      "o": [
        "Proposer un talk technique",
        "Accepter (il paie 200 €)"
      ],
      "ignore": "Le talk a lieu.",
      "tipT": "Pas de vente sur scène",
      "tipD": "Les GDG sont non-profit et indépendants : pas de formation payante ni de pitch déguisé."
    },
    "catering": {
      "title": "Combien de repas ?",
      "text": "Le traiteur veut un chiffre vendredi.",
      "o": [
        "75-80 % des inscrits confirmés",
        "Commander des pizzas le jour J"
      ],
      "ignore": "On improvisera.",
      "tipT": "Prévois pour les présents réels",
      "tipD": "Les événements gratuits perdent 28 % à 50 % d'inscrits. Commande pour 75-80 % du public prévu."
    },
    "kitav": {
      "title": "La boîte : audio et vidéo",
      "text": "Chaque speaker a un ordi différent.",
      "o": [
        "Adaptateurs et piles",
        "Adaptateurs seulement"
      ],
      "ignore": "Une boîte à moitié vide.",
      "tipT": "Le kit sauve la mise",
      "tipD": "Laptop, projecteur et micro incompatibles : le grand classique du jour J."
    },
    "kitlab": {
      "title": "Le Lab du codelab",
      "text": "24 ordis branchés pendant deux heures.",
      "o": [
        "Multiprises et un hotspot",
        "Vérifier le réseau avec l'IT"
      ],
      "ignore": "On verra dans le Lab.",
      "tipT": "Dimensionne le réseau au pic",
      "tipD": "Au moins 30 Mbps pour 100 personnes, +20-30 % de marge pour les 15 minutes critiques."
    },
    "prova": {
      "title": "Répète technique le vendredi ?",
      "text": "Tout le monde est crevé et bosse jusqu'à 18 h.",
      "o": [
        "Répète complète avec l'IT",
        "Installer seulement le Lab"
      ],
      "ignore": "On découvrira tout samedi.",
      "tipT": "Le vendredi sauve le samedi",
      "tipD": "Staff sur place 15 min avant avec checklist ; 5 min de battement ne suffisent jamais."
    },
    "checkin": {
      "title": "150 personnes en une demi-heure",
      "text": "La moitié arrive entre 9h00 et 9h30.",
      "o": [
        "QR et badges pré-imprimés",
        "Liste imprimée"
      ],
      "ignore": "Liste imprimée.",
      "tipT": "Le check-in, première impression",
      "tipD": "Les check-ins sur la plateforme valident l'affluence officielle. 1 000 personnes avec 15 bénévoles : 1h30."
    },
    "badgekit": {
      "title": "Et les personnes sans billet ?",
      "text": "Il y en aura. Toujours.",
      "o": [
        "Badges vierges en réserve",
        "À la main"
      ],
      "ignore": "Pas de badges en rab.",
      "tipT": "Sans RSVP",
      "tipD": "Une pile de badges vierges et des marqueurs évitent la file dans la file."
    },
    "speakercare": {
      "title": "Les speakers savent où aller ?",
      "text": "Ils viennent de trois régions.",
      "o": [
        "E-mail avec plan et contact",
        "Y a le groupe WhatsApp"
      ],
      "ignore": "Ils vont gérer.",
      "tipT": "Speakers chouchoutés, talks à l'heure",
      "tipD": "Demande aux speakers d'arriver 15-20 minutes en avance, avec un contact et un plan."
    },
    "riserva": {
      "title": "Et si un speaker annule ?",
      "text": "Ça arrive toujours. On ne sait jamais qui.",
      "o": [
        "Un talk de secours, prêt",
        "Lightning talk joker"
      ],
      "ignore": "On verra bien.",
      "tipT": "Prévois les désistements",
      "tipD": "Au moins un speaker manque à l'appel. Prépare le talk de secours comme les autres."
    },
    "overbooking": {
      "title": "Plus d'inscrits que de places",
      "text": "Fermer ou laisser ouvert ?",
      "o": [
        "1,5× les places + liste d'attente",
        "Laisse ouvert"
      ],
      "ignore": "On laisse ouvert.",
      "tipT": "Surbooker avec discernement",
      "tipD": "Pour un événement gratuit, vise 1,5 à 1,7× la jauge. Une caution remboursable booste la présence."
    },
    "antincendio": {
      "title": "Travaux sur le lieu ?",
      "text": "Personne n'a demandé le planning.",
      "o": [
        "Demande au lieu",
        "Qu'est-ce qui pourrait foirer"
      ],
      "ignore": "Personne ne demande.",
      "tipT": "Le calendrier du lieu",
      "tipD": "Alarmes incendie, ménage, fermetures : le lieu a un planning que tu ignores tant que tu ne demandes pas."
    },
    "stampa": {
      "title": "Le journal local veut venir",
      "text": "Il cherche quelqu'un à interviewer.",
      "o": [
        "Prépare un porte-parole",
        "S'ils viennent, on verra"
      ],
      "ignore": "On verra bien.",
      "tipT": "La presse est une opportunité",
      "tipD": "Un article local attire inscrits et sponsors pour l'an prochain : quelqu'un doit être prêt à parler."
    },
    "reminder": {
      "title": "J-7",
      "text": "Plein d'inscrits ont oublié qu'ils venaient.",
      "o": [
        "Rappel : « tu viens pas ? libère ta place »",
        "Une story Instagram"
      ],
      "ignore": "Pas de rappel.",
      "tipT": "Les rappels remplissent les salles",
      "tipD": "Les rappels réduisent le no-show. Les billets partent dans les 72 dernières heures : boucle à temps pour le traiteur."
    },
    "runofshow": {
      "title": "Qui fait quoi, minute par minute ?",
      "text": "Il y a le programme. Pas de déroulé staff.",
      "o": [
        "Déroulé et un lead par zone",
        "On improvise"
      ],
      "ignore": "Pas de déroulé.",
      "tipT": "Un responsable par zone",
      "tipD": "La communication explose en N(N-1)/2 : un déroulé partagé évite que tout repose sur une seule personne."
    },
    "premi": {
      "title": "Les sponsors envoient du swag",
      "text": "T-shirts, stickers, deux montres connectées.",
      "o": [
        "Tirage au sort en fin de journée",
        "Swag au check-in"
      ],
      "ignore": "Ça reste en régie.",
      "tipT": "L'après-midi se vide",
      "tipD": "Après le déj, une partie du public part. Une bonne raison de rester garde les salles pleines."
    },
    "segnaletica": {
      "title": "Le lieu est un labyrinthe",
      "text": "Trois étages, deux entrées, zéro panneau.",
      "o": [
        "Panneaux et un plan",
        "Les bénévoles vont gérer"
      ],
      "ignore": "Pas de panneaux.",
      "tipT": "Les gens se perdent",
      "tipD": "Quelqu'un de perdu interpelle le staff tous les deux mètres. La signalétique ne coûte rien."
    },
    "bar": {
      "title": "La cafétéria ferme à midi",
      "text": "Et pour l'après-midi ?",
      "o": [
        "Louer des machines à café",
        "La cafèt suffit"
      ],
      "ignore": "La cafèt suffit.",
      "tipT": "Le café est vital",
      "tipD": "C'est à la pause-café que le networking opère. Et que le staff recharge ses batteries."
    },
    "calendario": {
      "title": "Même jour qu'un autre DevFest",
      "text": "Tu le découvres via un post LinkedIn.",
      "o": [
        "Coordonnez : speakers et promo",
        "Que le meilleur gagne"
      ],
      "ignore": "Le public se divise.",
      "tipT": "Le calendrier appartient à tous",
      "tipD": "En 2025, trois DevFest italiens ont eu lieu le même jour. Un calendrier partagé entre chapters évite les clashs."
    },
    "stanchezza": {
      "title": "Tu n'as pas dormi depuis des jours",
      "text": "Boulot, DevFest, boulot, DevFest.",
      "o": [
        "Prends un week-end de pause",
        "Serre les dents"
      ],
      "ignore": "Serre les dents.",
      "tipT": "Le burnout est le vrai risque",
      "tipD": "« Bien plus de boulot que de fun », écrit un orga après cinq ans. Strange Loop s'est arrêté par épuisement."
    },
    "cani": {
      "title": "Le lieu borde un parc",
      "text": "Chiens en liberté, portes grandes ouvertes.",
      "o": [
        "Un bénévole à l'entrée",
        "Ils sont mignons, allez"
      ],
      "ignore": "Portes ouvertes.",
      "tipT": "Qui surveille l'entrée",
      "tipD": "Tout passe par l'entrée : public, prestataires, imprévus. Quelqu'un doit la garder."
    },
    "m_pizza": {
      "title": "Quarante pizzas ou soixante ?",
      "text": "70 inscrits, 50 places.",
      "o": [
        "Commande pour les présents, heure fixe",
        "On appellera à 20h"
      ],
      "ignore": "On appelle à 20h.",
      "tipT": "Des pizzas pour ceux qui sont là",
      "tipD": "Un meetup, c'est 100-250 € de buffet par mois. Commande selon l'affluence prévue, pas les inscrits."
    },
    "m_porta": {
      "title": "Qui ouvre la salle à 18h ?",
      "text": "Le gardien a les clés. Mais finit à 17h.",
      "o": [
        "Organise-toi, prends les clés",
        "Espérons qu'il reste"
      ],
      "ignore": "Tout le monde attend dehors.",
      "tipT": "Chaque lieu a son gardien",
      "tipD": "Douze lieux par an, c'est douze gardiens à connaître par leur prénom."
    },
    "m_promo": {
      "title": "Le post du meetup a 3 likes",
      "text": "J-10.",
      "o": [
        "Écris aux anciens participants",
        "Reposte-le"
      ],
      "ignore": "Toujours 3 likes.",
      "tipT": "Ceux qui sont venus reviennent",
      "tipD": "Faire grandir un meetup prend des années de régularité. Commence par ceux qui sont déjà venus."
    },
    "m_speaker": {
      "title": "Le speaker veut 90 minutes",
      "text": "Le créneau est de 40.",
      "o": [
        "Panneau de temps et modérateur",
        "Laisse-le parler"
      ],
      "ignore": "Il parlera autant qu'il veut.",
      "tipT": "Les talks débordent",
      "tipD": "5 minutes d'interlude ne suffisent jamais : il faut quelqu'un pour surveiller le chrono."
    },
    "sj_quota": {
      "title": "Le codelab utilise l'API Gemini",
      "text": "Trente personnes, une seule clé.",
      "o": [
        "Crédits et clés de secours",
        "Chacun prend la sienne"
      ],
      "ignore": "Chacun prend la sienne.",
      "tipT": "Les quotas sautent toujours en direct",
      "tipD": "En codelab, tout le monde appelle la même API à la même minute : prépare crédits et clés persos."
    },
    "sj_aule": {
      "title": "24 places au Lab, 60 inscrits",
      "text": "Tout le monde veut le codelab.",
      "o": [
        "Deux sessions et liste d'attente",
        "On va se serrer"
      ],
      "ignore": "On se serre.",
      "tipT": "Les vraies places ont une prise",
      "tipD": "En codelab, la limite n'est pas le nombre de chaises : ce sont les prises et le réseau."
    },
    "io_stream": {
      "title": "La keynote en direct",
      "text": "Projecteur, son, stream depuis l'autre bout du monde.",
      "o": [
        "Teste avec une vidéo de 2h",
        "Ça va le faire"
      ],
      "ignore": "Ça va le faire.",
      "tipT": "Le stream, ça se teste",
      "tipD": "Son, réseau et projecteur se testent ensemble, et longtemps : les bugs arrivent à la 40e minute."
    },
    "io_vip": {
      "title": "L'élu veut faire un mot",
      "text": "Cinq minutes. Soi-disant.",
      "o": [
        "Fixe l'horaire et la durée",
        "On improvisera"
      ],
      "ignore": "Il viendra quand il voudra.",
      "tipT": "Accueillir les institutions",
      "tipD": "Un mot officiel aide la communauté, à condition de fixer l'heure et la durée à l'avance."
    }
  },
  "chat": {
    "fx": {
      "parking": [
        "Le speaker entre par le bon côté : il ne se perdra pas.",
        "Il suit les panneaux : doigts croisés.",
        "Pas de réponse : le speaker va se perdre dans les couloirs."
      ],
      "adapter": [
        "Adaptateur prêt sur scène : pas d'écran noir.",
        "Il va se débrouiller : garde un œil sur la scène.",
        "Pas de réponse : il va arriver sans adaptateur."
      ],
      "logo": [
        "Logo corrigé : le sponsor est ravi.",
        "Le sponsor fait la grimace.",
        "Pas de réponse : le sponsor vient râler."
      ],
      "coffeeLow": [
        "Plus de café arrive.",
        "Le café va bientôt manquer.",
        "Pas de réponse : le café va bientôt manquer."
      ],
      "queueHelp": [
        "Un bénévole fonce au check-in.",
        "La file s'allonge.",
        "Pas de réponse : la file s'allonge de fou."
      ],
      "pizzaTime": [
        "Commande confirmée : les pizzas arrivent à l'heure.",
        "Espérons qu'elles arrivent à l'heure.",
        "Pas de réponse : espérons qu'elles arrivent à l'heure."
      ],
      "wifiPass": [
        "Mot de passe partagé : tout le monde est content.",
        "Réponse un peu vague, mais ça passe.",
        "Pas de réponse : les gens râlent."
      ],
      "vipCall": [
        "Accueil au top : l'invité arrive serein.",
        "On verra bien comment ça se passe.",
        "Pas de réponse : l'invité débarque à l'improviste."
      ],
      "mom": [
        "Maman est rassurée et tu souffles un peu.",
        "Maman s'en contente.",
        "Maman réessaiera plus tard."
      ],
      "lostThing": [
        "Objet retrouvé : note en hausse !",
        "Tant pis.",
        "Pas de réponse : le participant est déçu."
      ],
      "kidsWhere": [
        "Coin enfants indiqué : aucun enfant perdu.",
        "On verra bien comment ça se passe.",
        "Pas de réponse : le parent est déçu."
      ],
      "teamStuck": [
        "Un mentor arrive : l'équipe repart.",
        "L'équipe galère toute seule.",
        "Pas de réponse : l'équipe reste bloquée."
      ]
    },
    "acts": {
      "kidsWhere": [
        {
          "from": "Participant",
          "text": "Où est l'espace enfants ? Ma fille veut jouer",
          "r": [
            "Un bénévole vous accompagne",
            "Au fond de l'expo"
          ]
        },
        {
          "from": "Elisa (speaker)",
          "text": "Je peux laisser mon petit quelque part pendant mon talk ?",
          "r": [
            "Oui, il y a l'espace enfants",
            "Emmène-le en salle"
          ]
        }
      ],
      "teamStuck": [
        {
          "from": "Équipe 7",
          "text": "Le déploiement plante depuis deux heures, un mentor dispo ?",
          "r": [
            "Un mentor arrive",
            "Essaie de redémarrer"
          ]
        },
        {
          "from": "Équipe 3",
          "text": "Besoin d'aide avec les API, on est bloqués",
          "r": [
            "Je vous envoie quelqu'un",
            "Lisez la doc"
          ]
        }
      ],
      "parking": [
        {
          "from": "Sara (speaker)",
          "text": "Je suis au parking, j'entre par où ? 🚗",
          "r": [
            "Entrée latérale, je viens vers toi",
            "Suis les panneaux !"
          ]
        },
        {
          "from": "Marco (speaker)",
          "text": "Mon GPS m'amène dans un champ. C'est normal ?",
          "r": [
            "Je t'envoie la position et un bénévole",
            "Demande au bar"
          ]
        }
      ],
      "adapter": [
        {
          "from": "Davide (speaker)",
          "text": "J'ai que de l'USB-C. Vous avez un adaptateur HDMI ?",
          "r": [
            "Je te l'apporte sur scène",
            "Demande au public"
          ]
        },
        {
          "from": "Anna (speaker)",
          "text": "Mon ordi ne détecte pas le projecteur 😰",
          "r": [
            "J'arrive avec le kit",
            "Redémarre et prie"
          ]
        }
      ],
      "logo": [
        {
          "from": "Sponsor",
          "text": "Notre logo sur les slides d'ouverture est trop petit",
          "r": [
            "Je l'agrandis tout de suite",
            "Après le déj"
          ]
        }
      ],
      "coffeeLow": [
        {
          "from": "Luca (bénévole)",
          "text": "Presque plus de café ☕☕☕",
          "r": [
            "Ouvre le stock en régie",
            "Rationne"
          ]
        }
      ],
      "queueHelp": [
        {
          "from": "Giada (check-in)",
          "text": "On est sous l'eau au check-in, à l'aide !!!",
          "r": [
            "Je t'envoie un bénévole",
            "Tiens bon 5 minutes"
          ]
        }
      ],
      "pizzaTime": [
        {
          "from": "Pizzeria",
          "text": "Les pizzas pour quelle heure ? Et l'adresse exacte ?",
          "r": [
            "12h30, entrée principale",
            "Je vous rappelle"
          ]
        }
      ],
      "wifiPass": [
        {
          "from": "Participant",
          "text": "C'est quoi le mot de passe du Wi-Fi ?",
          "r": [
            "C'est au dos du badge !",
            "Demande au point info"
          ]
        }
      ],
      "vipCall": [
        {
          "from": "Mairie",
          "text": "L'élu passera à 11h pour dire bonjour",
          "r": [
            "On l'accueille à l'entrée",
            "OK, on verra"
          ]
        }
      ],
      "mom": [
        {
          "from": "Maman",
          "text": "Tu as mangé ? Je t'ai vu sur Instagram, tu as l'air fatigué",
          "r": [
            "Oui maman ❤️",
            "Plus tard"
          ]
        }
      ],
      "lostThing": [
        {
          "from": "Participant",
          "text": "J'ai perdu mon chargeur de PC en Salle B",
          "r": [
            "On regarde, passe au point info",
            "Vois avec le bar"
          ]
        }
      ]
    },
    "noise": [
      {
        "from": "Luca (bénévole)",
        "text": "Qui a pris les clés de la Salle B ?"
      },
      {
        "from": "Giada (check-in)",
        "text": "Un type dit qu'il est inscrit mais il est pas sur la liste 🙃"
      },
      {
        "from": "Photographe",
        "text": "Il me faut quelqu'un pour la photo de groupe à 16h"
      },
      {
        "from": "Sponsor",
        "text": "Encore des tote bags ? On en a plus"
      },
      {
        "from": "Paolo (speaker)",
        "text": "Je peux faire une démo live ? Il me faut du bon net"
      },
      {
        "from": "Co-org",
        "text": "Qui a le chargeur du micro ?"
      },
      {
        "from": "Gardien",
        "text": "Je ferme à 18h30, je vous préviens"
      },
      {
        "from": "Luca (bénévole)",
        "text": "Plus de pin's 😭"
      },
      {
        "from": "Participant",
        "text": "On peut se garer dans la cour ?"
      },
      {
        "from": "Giada (check-in)",
        "text": "Badge de John Smith imprimé trois fois. Trois John Smith différents."
      },
      {
        "from": "Co-org",
        "text": "Le groupe Telegram a explosé, 300 messages"
      },
      {
        "from": "Traiteur",
        "text": "On laisse les bouteilles d'eau à l'entrée"
      },
      {
        "from": "Sara (speaker)",
        "text": "Je peux réorganiser mes slides en dernière minute ?"
      },
      {
        "from": "Bénévole",
        "text": "Y a plus de papier aux toilettes (je dis ça, je dis rien)"
      },
      {
        "from": "Photographe",
        "text": "La lumière dans le Grand Amphi est une catastrophe"
      },
      {
        "from": "Participant",
        "text": "Il y a une salle d'allaitement ?"
      },
      {
        "from": "Sponsor",
        "text": "Notre roll-up est tombé. Encore."
      },
      {
        "from": "Co-org",
        "text": "N'oubliez pas les photos pour les réseaux !!"
      }
    ],
    "from": {
      "volunteer": "Bénévole",
      "speaker": "Speaker",
      "sponsor": "Sponsor",
      "pizzeria": "Pizzeria",
      "attendee": "Participant",
      "city": "Mairie",
      "mom": "Maman"
    }
  },
  "banter": [
    "Pardon, où est la Salle B ?",
    "Le Wi-Fi ?",
    "Reste du café ?",
    "Tu peux imprimer mon badge ?",
    "Vous partagerez les slides ?",
    "Où sont les toilettes ?",
    "Des stickers ?",
    "Petite question rapide ?",
    "On mange à quelle heure ?",
    "Le talk sur l'IA est complet ?",
    "T'as un chargeur ?",
    "Super orga !",
    "On peut faire une photo ?",
    "Où sont les t-shirts ?"
  ],
  "chaos": {
    "firedrill": {
      "title": "Alarme incendie !",
      "text": "Exercice surprise : tout le monde dehors pour quelques minutes."
    },
    "firedrillEnd": "Fin de l'alerte : on rentre. Les talks reprennent avec du retard."
  },
  "radio": {
    "hostPaused": "L'hôte a mis en pause.",
    "kid": "🧸 Un enfant s'est éloigné de l'espace enfants !",
    "access": "♿ L'ascenseur est en panne : une personne a besoin de l'accès PMR.",
    "noise": "📢 Les voisins se plaignent du bruit !",
    "locked": "Porte fermée : personne n'a géré les clés. Le gardien arrive…",
    "unlocked": "Le gardien est là : on ouvre !",
    "open": "Portes ouvertes ! Check-in en bas à droite, boîte GDG en régie.",
    "controls": "Touche un problème : tu y vas et tu gères.",
    "controlsDuo": "J1 : WASD + Espace. J2 : flèches + Entrée.",
    "speakerLost": "{name} n'est pas en salle speakers : trouve-le et amène-le sur scène.",
    "coc": "Une personne signale un comportement inapproprié. Vas-y tout de suite.",
    "cancel": "Le speaker de {t} ne vient pas. Improvise !",
    "pizza": "Le livreur tourne autour du bâtiment : file à l'entrée.",
    "escalate": "{p} : trop tard.",
    "noTool": "{tool} : pas dans la boîte.",
    "late": "En retard : {t}",
    "talkCancel": "Talk annulé : « {t} ».",
    "lunchLate": "Le déj arrive froid et en retard.",
    "lunch": "À table !",
    "murphy": "😈 Murphy est là : stoppe-le avant qu'il n'atteigne {where} !",
    "sabotage": "😈 Murphy a frappé : {where}.",
    "burnout": "😵‍💫 Burnout : les orgas aussi ont besoin de pauses.",
    "raffle": "🎁 Tirage au sort !",
    "photo": "📸 Photo de groupe !",
    "synergy": "🤝 À deux, c'est plus rapide.",
    "backup": "🦸 Le backup sauve le talk.",
    "improvised": "🎤 Talk improvisé : standing ovation !",
    "leave": "🚶 {n} personnes s'en vont ({why}).",
    "why": {
      "coda": "la file d'attente",
      "overflow": "salle comble",
      "afternoon": "après le déj"
    },
    "stream": "📺 Stream lancé dans le hall.",
    "assign": "On l'envoie où ? Touche un souci ou un poste (cercles verts).",
    "orgPick": "Où envoies-tu {name} ? Touche un problème.",
    "orgSent": "{name} s'en occupe.",
    "volSent": "Un bénévole file vers : {post}.",
    "volCant": "Les bénévoles ne peuvent pas gérer ça : vas-y toi-même ou envoie le co-org.",
    "end": "🎉 C'est plié ! On éteint les lumières, on ouvre les chats.",
    "paused": "⏸️ L'hôte a mis en pause.",
    "guest": "Tu es dans la session de l'hôte.",
    "dog": "🐕 Un chien est entré dans la salle !",
    "vip": "🎖️ Visite surprise à l'entrée !",
    "press": "🎙️ Le journal local est dans l'expo.",
    "blackout": "💡 Coupure de courant : {where} !",
    "panic": "Trop d'un coup : respire, choisis, délègue.",
    "chatMissed": "Message ignoré : {who}.",
    "abilityNone": "Aucun souci tech à régler là : le hotfix reste chargé.",
    "rush": "Coup de feu ! {n} galères d'un coup : règle tout avant que ça dégénère.",
    "rushWon": "Coup de feu géré ! La note s'envole.",
    "rushLost": "Heure de pointe ratée : la prochaine va frapper plus fort."
  },
  "quips": {
    "fixed": [
      "Réglé !",
      "Fait !",
      "Bien joué !",
      "Géré !"
    ],
    "hdmi": [
      "Signal !",
      "Ça affiche !"
    ],
    "wifi": [
      "Redémarré !",
      "En ligne !"
    ],
    "coffee": [
      "Café !"
    ],
    "pizza": [
      "Pizza là !"
    ],
    "speaker": [
      "Trouvé !",
      "Sur scène !"
    ],
    "dog": [
      "Bon toutou !"
    ],
    "press": [
      "En une !"
    ],
    "flame": [
      "Paix faite."
    ],
    "prevent": [
      "À temps !"
    ],
    "escalate": [
      "Trop tard !",
      "Aïe !"
    ],
    "found": "Je t'ai !",
    "murphy": "Murphy déjoué !"
  },
  "lessons": {
    "kids": [
      "Un vrai coin enfants",
      "Sans espace surveillé, les enfants errent partout. Une animatrice et un bénévole dédié changent tout."
    ],
    "access": [
      "L'accessibilité s'anticipe",
      "Une visite avec une personne en fauteuil repère en une heure ce qui coûte cher le jour J."
    ],
    "photo": [
      "Droit à l'image",
      "Tours de cou de couleur : rouge pas de photo, jaune demande, vert ok. Le photographe sait dès le premier cliché."
    ],
    "mentors": [
      "Les mentors font le hackathon",
      "Sans mentors, les équipes bloquent des heures. Il faut des roulements, même la nuit."
    ],
    "night": [
      "La nuit s'organise",
      "Des tours de garde, une salle de repos et de la vraie nourriture : la fin de nuit décide des démos."
    ],
    "rules": [
      "Règles et critères publics",
      "Si les critères sont improvisés, le verdict sera contesté."
    ],
    "hdmiKit": [
      "Un kit d'adaptateurs coûte moins qu'un talk annulé",
      "Chaque écran noir a coûté de précieuses minutes : {n} fois aujourd'hui."
    ],
    "hdmiStage": [
      "Laisse le kit en salle",
      "Les adaptateurs étaient là, mais en régie. Un kit par salle évite bien des soucis."
    ],
    "speakers": [
      "Les speakers méritent un accueil",
      "Un mail avec plan, une arrivée 15-20 min avant et un bénévole à l'accueil."
    ],
    "backup": [
      "Un speaker de secours, prêt",
      "Prévois un désistement : un remplaçant transforme un trou en talk réussi."
    ],
    "queue": [
      "Le check-in donne le ton",
      "La file a atteint {n}. Un QR et deux bénévoles dès 8h45."
    ],
    "wifi": [
      "Calibre le réseau pour le pic",
      "30 Mbps pour 100 personnes, validés avec l'IT, plus un hotspot de secours."
    ],
    "lunch": [
      "Confirme le déjeuner la veille",
      "75-80 % des présences attendues, à heure fixe."
    ],
    "coc": [
      "Tout signalement mérite une réponse immédiate",
      "Des contacts formés, identifiables, et une procédure connue de l'équipe."
    ],
    "cocOk": [
      "Le CoC a fonctionné",
      "Quelqu'un a su réagir. C'est tout l'intérêt de la formation."
    ],
    "burnout": [
      "L'équipe a aussi besoin de pauses",
      "Des roulements et une pause café pour le staff ne sont pas un luxe."
    ],
    "tavoli": [
      "Certaines tâches ne se gèrent pas en solo",
      "Déléguer et préparer la veille évite de se retrouver coincé."
    ],
    "delegate": [
      "Fais bouger tes bénévoles",
      "Délègue selon le rythme : check-in le matin, pauses café l'après-midi."
    ],
    "novols": [
      "Aucun événement ne tourne sans aide",
      "Sans bénévoles, chaque file était pour toi. Recrute un mois avant."
    ],
    "overflow": [
      "L'overbooking avec discernement",
      "Liste d'attente, rappels et retransmission entre les salles."
    ],
    "murphy": [
      "Murphy existe",
      "Quelque chose va rater : un bon déroulé staff permet de le voir venir."
    ],
    "afternoon": [
      "L'après-midi se vide",
      "{n} personnes sont parties plus tôt : donne-leur une raison de rester."
    ],
    "turnout": [
      "Les salles se remplissent des mois avant",
      "{n} personnes en salle : communique deux mois plus tôt, en comptant les no-shows."
    ],
    "chat": [
      "Le chat, c'est la moitié du job",
      "{n} messages ignorés : chacun était un problème en approche."
    ],
    "clean": [
      "Une journée sans accroc",
      "La préparation a payé. Note bien ce qui a marché."
    ],
    "interrupt": [
      "Tout le monde cherche le lead",
      "On t'a coupé {n} fois : points d'info et signalétique libèrent l'équipe."
    ]
  },
  "retro": {
    "h3": [
      "{ev} {city} : standing ovation",
      "{present} personnes, {ontime} sessions à l'heure et un staff au taquet."
    ],
    "h2": [
      "{ev} {city} : quelques couacs, mais quelle commu !",
      "Le public repart ravi ; le staff, un peu moins reposé."
    ],
    "h1": [
      "Le chaos à {ev} {city}, mais la commu tient bon",
      "La journée se termine, de justesse. Rétro demain."
    ],
    "h0": [
      "{ev} {city} : à oublier d'urgence",
      "« Plus jamais sans adaptateurs », jure le staff."
    ],
    "few": [
      "{ev} {city} : top, mais en comité restreint",
      "Retours {fb}, mais seulement {present} dans la salle : la comm' aussi rapporte des étoiles."
    ],
    "anon": {
      "h3": "{ev} : standing ovation",
      "h2": "{ev} : quelques couacs, mais quelle commu !",
      "h1": "Le chaos au {ev}, mais la commu a tenu",
      "h0": "{ev} : à oublier",
      "few": "{ev} : top, mais en petit comité"
    },
    "q": [
      "Quel a été le pire moment de chaos ? Ça vous est déjà arrivé en vrai ?",
      "Qu'y a-t-il dans la boîte de votre chapter aujourd'hui ?",
      "Quel problème avez-vous sciemment laissé couler ?",
      "Si vous deviez refaire les préparatifs, vous changeriez quoi ?"
    ],
    "qBurnout": "Qui a fini en burnout, et pourquoi ?",
    "qChat": "Combien de messages as-tu ignorés ? Qui gère le chat le jour J ?"
  },
  "coach": {
    "welcome": [
      "Bienvenue sur place !",
      "Le jeu se met en pause dès qu'un imprévu survient. Lis à ton rythme, puis appuie sur Compris (ou Entrée)."
    ],
    "you": [
      "C'est toi",
      "Touche un point sur la carte pour t'y rendre (clavier : WASD ou flèches). Touche un problème et tu iras le régler tout seul."
    ],
    "checkin": [
      "Le check-in",
      "Les gens arrivent ici. Si la file s'allonge, touche le comptoir : reste là et gère les entrées."
    ],
    "goals": [
      "Objectifs du jour",
      "{list}. Chacun vaut une étoile : elles débloquent le prochain événement et le kit du chapter."
    ],
    "rating": [
      "La note de satisfaction",
      "Elle monte quand tout roule et baisse si un souci s'aggrave ou qu'un talk saute. Verdict à la fin."
    ],
    "problem": [
      "Un problème !",
      "Le cercle indique le temps restant avant que la situation n'empire. Touche l'icône : va le régler. L'arc vert montre la progression."
    ],
    "tool": [
      "Il te faut un outil",
      "{tool} : il est dans la boîte GDG, en régie. Touche le problème et tu le prendras au passage. En manuel : entre dans le cercle en pointillés et choisis l'outil dans la barre en bas."
    ],
    "map": [
      "Tout le lieu",
      "Ici en bas, tu vois tout le bâtiment : les points sont des problèmes, le cadre blanc montre ta vue. Touche un endroit et ton orga y va."
    ],
    "noTool": [
      "Outil manquant",
      "Personne n'a mis {tool} dans la boîte pendant le Countdown. Tu peux improviser, mais c'est plus long : prépare-le la prochaine fois."
    ],
    "crew": [
      "Besoin d'un coup de main",
      "Il faut être deux ici : amène un bénévole (touche-le, puis touche l'endroit) ou bosse avec ton co-orga."
    ],
    "warn": [
      "Le triangle jaune",
      "Un souci se prépare. Passe dessus avant qu'il n'éclate pour l'éviter : bien plus rentable que de réparer."
    ],
    "chat": [
      "Le chat du staff",
      "À ne pas juste lire : chaque réponse change un truc sur place (speaker guidé, bénévole au check-in, rab de café). Réponds avec Q ou E, ou tape, avant la fin de la barre : si tu ignores, place au hasard."
    ],
    "murphy": [
      "Murphy !",
      "Le démon des pannes part saboter un truc. Touche-le et attrape-le avant qu'il n'arrive : il fuira et ça te rapporte des points."
    ],
    "panic": [
      "LE CHAOS !",
      "Quatre problèmes d'un coup. Respire : d'abord le cercle le plus vide, puis le reste. Les bénévoles aident."
    ],
    "firedrill": [
      "Alerte incendie",
      "Tout le monde évacue quelques secondes et les talks s'arrêtent. On attend (et la prochaine fois, demande le planning des alertes au lieu)."
    ],
    "goalOk": [
      "Objectif atteint !",
      "{goal} : cette étoile est à toi. Les autres objectifs sont tout en haut."
    ],
    "goalFail": [
      "Objectif manqué",
      "{goal} : pas pour cette fois. Tu peux encore choper les autres étoiles."
    ],
    "burnout": [
      "Burnout",
      "À plat d'énergie, tu es à l'arrêt. Bois un café avant d'être à sec : la jauge est en haut à droite."
    ],
    "energy": [
      "Énergie basse",
      "Le staff, ça épuise. Fais une pause au café (au centre du hall) ou en salle des speakers pour recharger, avant le burnout."
    ],
    "vols": [
      "Les bénévoles",
      "À leur poste, ils gèrent le public : café, réponses, accueil, et la note monte. Touche un bénévole, puis un problème ou un poste (cercles verts) pour le placer."
    ],
    "rush": [
      "Coup de feu",
      "Plein de galères d'un coup, avec un ⚡. Règle tout avant que ça n'empire et la note s'envole. Répartissez-vous : envoie le co-orga et les bénévoles."
    ],
    "ability": [
      "Ta compétence : {name}",
      "Le bouton jaune en haut (F au clavier) : {what} Ensuite ça recharge, sers-t'en au bon moment."
    ],
    "mate": [
      "Ton co-orga",
      "Gère en solo, mais obéit aux ordres : touche-le, puis touche un problème et il y va. Toi, gère autre chose."
    ],
    "waiting": [
      "Le talk est bloqué",
      "Il faut le speaker sur scène et un projecteur qui marche. Chaque minute d'attente coûte de la note ; après 26 minutes, le talk saute."
    ],
    "night": [
      "En pleine nuit",
      "Entre 1h et 6h, l'énergie file plus vite. Relayez-vous au café ou en salle de repos, si tu en as préparé une."
    ],
    "locked": [
      "Porte close",
      "Personne n'a prévenu le gardien : les gens attendent dehors. La prochaine fois, prévois la carte des clés dans le Countdown."
    ],
    "ev:meetup": [
      "Meetup du jeudi",
      "Une salle, deux talks, quarante pizzas. Le niveau le plus posé : teste les commandes tranquille."
    ],
    "ev:studyjam": [
      "La Study Jam",
      "Codelab dans le Lab : multiprises, Wi-Fi et crédits cloud sont ton quotidien. Deux salles ouvertes."
    ],
    "ev:wtm": [
      "Women Techmakers",
      "L'accueil avant tout : enfants qui s'égarent, droit à l'image, accès PMR. On n'oublie personne."
    ],
    "ev:ioext": [
      "Google I/O Extended",
      "Keynote en direct, salle comble, VIP en route. La grande soirée des livestreams."
    ],
    "ev:hack": [
      "Le hackathon nocturne",
      "De 18h à 10h. Les équipes bloquées (🧩) attendent un mentor, pizza à minuit, démos à 8h."
    ],
    "ev:devfest": [
      "Le DevFest",
      "Trois salles, quinze sessions et Murphy. Tout ce que tu as appris, d'un coup."
    ],
    "tPrepWeeks": [
      "Le compte à rebours",
      "Plus que quelques semaines : chaque round prépare la suite. Tes choix déterminent le début du jour J."
    ],
    "tPrepPips": [
      "Tes soirées libres",
      "Chaque point est une soirée. Les options coûtent de 0 à 2 points : impossible de tout faire."
    ],
    "tPrepOpt": [
      "Choisis",
      "Touche une option pour t'en occuper. Les étiquettes vertes et rouges indiquent l'impact."
    ],
    "tPrepIgnore": [
      "Si personne ne s'en charge",
      "Ce que tu laisses de côté arrive quand même : voici quoi. Parfois, ignorer est le bon choix."
    ],
    "tPrepMeters": [
      "Les comptes du chapter",
      "Budget, RSVP, communauté, partenaires et énergie : regarde-les évoluer."
    ],
    "tPrepClose": [
      "Terminer le round",
      "Une fois décidé, valide : tu verras le résultat et ce que tu as appris."
    ],
    "tLoStats": [
      "La veille",
      "Ce avec quoi tu attaques la journée : participants prévus, bénévoles, énergie, budget."
    ],
    "tLoGoals": [
      "Les objectifs",
      "Trois objectifs, trois étoiles. Tu les verras aussi en haut pendant l'événement."
    ],
    "tLoGo": [
      "Ouverture des portes !",
      "Quand tu es prêt, ouvre les portes. Le jeu fera une pause pour t'expliquer les nouveautés."
    ],
    "tSeasonEv": [
      "La saison",
      "Six événements, du meetup au DevFest. Trois objectifs par événement : une étoile débloque le suivant."
    ],
    "tSeasonKit": [
      "Le kit du chapter",
      "Dépense tes étoiles ici pour des améliorations valables sur tous les événements."
    ],
    "p": {
      "queue": "File d'attente à l'entrée. Touche le comptoir du check-in et reste là, ou envoie un bénévole.",
      "stampante": "L'imprimante à badges est bloquée : le check-in ralentit. Va vite la réparer.",
      "speaker": "Le speaker est perdu dans le hall. Rejoins-le : il te suit. Guide-le jusqu'à la scène (cercle vert).",
      "hdmi": "L'ordi du speaker ne se connecte pas. En un éclair avec les adaptateurs de la boîte ; sinon, improvise.",
      "mic": "Le micro faiblit. Prends des piles dans la boîte, puis file sur scène.",
      "wifi": "Le Wi-Fi est tombé : redémarre la baie en régie, ou lance le hotspot dans le Lab.",
      "prese": "Plus de prises dans le Lab. Les multiprises sont dans la boîte.",
      "coffee": "Le café est presque épuisé. Remplis les machines au stand café.",
      "pizza": "Le livreur est à l'entrée avec les pizzas. Récupère-les avant qu'elles ne refroidissent.",
      "overflow": "La salle est pleine et ça bloque dehors. À la porte : dis-leur de regarder le stream dans le hall.",
      "sponsor": "Le sponsor veut te parler, maintenant. Rejoins son stand.",
      "perso": "Quelqu'un cherche sa salle. Une réponse rapide et le voilà rassuré.",
      "coc": "Signalement CoC. Priorité absolue : file tout de suite, écoute, protège.",
      "cancel": "Le speaker ne vient pas. Sur scène, tu peux improviser (lightning talks, Q&A) : gère ça là-bas.",
      "tavoli": "Il faut réaménager le Lab pour le prochain atelier : besoin d'un bras en plus.",
      "overrun": "Le speaker dépasse son temps. Monte sur scène avec le panneau « 5 minutes ».",
      "vip": "Un VIP arrive à l'entrée. Accueille-le avant qu'il ne se sente délaissé.",
      "dog": "Un chien dans la salle ! Rejoins-le : il te suit. Conduis-le vers la sortie.",
      "press": "Un journaliste veut une interview : belle opportunité, ça vaut des points.",
      "flame": "Tabulations contre espaces, le retour. Sépare-les avant que ça ne dégénère.",
      "blackout": "Panne de courant dans une salle : réenclenche le disjoncteur en régie.",
      "quota": "Plus de crédits Cloud pendant le codelab ! Vite réglé s'il t'en reste dans la boîte.",
      "stream": "Plus de son sur le stream : règle l'audio à la régie.",
      "badge": "Plus de badges au check-in. Prends des rechanges dans la boîte ou écris-les à la main.",
      "kid": "Un enfant s'est éloigné de l'espace enfants. Rejoins-le calmement et ramène-le.",
      "access": "Ascenseur en panne : guide le participant vers la Grande Salle via l'accès PMR.",
      "foto": "Le photographe shoote des gens qui refusent les photos. Va lui parler : le consentement compte.",
      "mentor": "Une équipe est bloquée (build rouge, API muette). Un mentor la débloque : le Tech va deux fois plus vite.",
      "noise": "Les voisins se plaignent du bruit. File à l'entrée calmer le jeu."
    }
  },
  "perks": {
    "walkie": {
      "name": "Walkies-talkies",
      "desc": "Le chat du staff attend 50 % plus longtemps."
    },
    "qr": {
      "name": "Lecteur QR",
      "desc": "Check-in rapide à chaque événement."
    },
    "kit": {
      "name": "Kit AV",
      "desc": "Adaptateurs et piles toujours dans la boîte."
    },
    "signs": {
      "name": "Panneaux réutilisables",
      "desc": "Moins de gens perdus, moins de questions dans le couloir."
    },
    "moka": {
      "name": "Moka géante",
      "desc": "Plus de café à chaque événement."
    },
    "shoes": {
      "name": "Chaussures confortables",
      "desc": "Tu marches 12 % plus vite."
    },
    "squad": {
      "name": "Équipe de vétérans",
      "desc": "Un bénévole de plus à chaque événement."
    },
    "colead": {
      "name": "Co-organisateur",
      "desc": "En solo ? Quelqu'un vient toujours t'aider."
    }
  },
  "help": {
    "title": "Comment jouer",
    "steps": [
      [
        "🃏",
        "Prépare",
        "Peu de soirs libres, trop à faire. Ce que personne ne gère arrive quand même."
      ],
      [
        "🏃",
        "Survis",
        "Touche un problème : tu y vas et tu gères. Le triangle jaune s'évite, le coup de feu ⚡ se gagne. Trois objectifs, trois étoiles."
      ],
      [
        "👉",
        "Délègue",
        "Touche le co-org ou un bénévole, puis un souci : il y va. Un bénévole à son poste sert du café, des réponses et des sourires."
      ],
      [
        "💬",
        "Réponds",
        "Le chat du staff ne dort jamais : tape une réponse."
      ],
      [
        "📰",
        "Débriefe",
        "La rétro : ce qui s'est passé, les leçons à retenir."
      ]
    ],
    "keys": "Clavier : WASD/flèches + Space · 1-4 outils · Q/E réponses · F capacité · P pause · M son",
    "table": "Les problèmes"
  },
  "venues": {
    "uni": {
      "name": "Université",
      "desc": "Trois salles et plein d'espace. Le Wi-Fi fait ce qu'il peut."
    },
    "cowork": {
      "name": "Coworking",
      "desc": "Super Wi-Fi et vraie cuisine ; petites salles, gère les places.",
      "open": "Portes ouvertes ! Accueil en bas au centre, boîte GDG dans le bureau (en bas à gauche).",
      "rooms": {
        "A": "Cabine acoustique",
        "B": "Salle plénière",
        "L": "Salle de réunion",
        "H": "Open space",
        "R": "Bureau",
        "S": "Espace détente",
        "E": "Cuisine",
        "K": "Accueil"
      }
    }
  },
  "medals": {
    "chat0": [
      "Chat propre",
      "aucun message ignoré, au moins trois réponses"
    ],
    "speakers": [
      "Personne ne se perd",
      "aucun talk sauté et aucun speaker perdu"
    ],
    "onTime": [
      "Montre suisse",
      "tous les talks à l'heure"
    ],
    "rushAll": [
      "Heure de pointe",
      "tous les coups de feu gérés (au moins deux)"
    ],
    "prevent": [
      "Clairvoyant",
      "cinq pépins anticipés"
    ],
    "murphy": [
      "Chasseur de Murphy",
      "Murphy contré deux fois en une journée"
    ],
    "team": [
      "Capitaine d'équipe",
      "huit tâches confiées aux co-orgs et bénévoles"
    ],
    "ability": [
      "As dans la manche",
      "quatre compétences utilisées en une journée"
    ],
    "noBurnout": [
      "Zen",
      "un hackathon ou DevFest sans burnout"
    ],
    "devfest3": [
      "DevFest parfait",
      "trois étoiles au DevFest"
    ],
    "soldout3": [
      "Complet",
      "trois étoiles à guichets fermés"
    ],
    "weekly": [
      "Hebdo",
      "un défi de la semaine joué"
    ],
    "season": [
      "Saison complète",
      "au moins une étoile sur chaque événement"
    ]
  },
  "abilities": {
    "lead": [
      "Mégaphone",
      "annonce dans le hall : le check-in carbure et personne ne t'arrête pendant un moment."
    ],
    "tech": [
      "Hotfix",
      "règle instantanément le bug tech le plus urgent, où qu'il soit."
    ],
    "host": [
      "Combler le vide",
      "pendant un moment, les retards en salle ne coûtent pas de note."
    ],
    "care": [
      "Pause souffle",
      "+25 d'énergie pour ceux près de toi, et les flame wars se calment."
    ]
  },
  "about": {
    "title": "Le projet",
    "p1": "Quiconque organise des événements tech apprend les mêmes leçons à la dure : l'ordi sans USB-C, le sponsor fantôme, la moitié des inscrits absents. Overbooked! en fait un jeu coop, avec une rétro guidée à la fin.",
    "p2": "Situations et conseils viennent d'expériences vécues d'organisateurs : chaque conseil cite sa source. Avec Gemini, le jeu génère cartes, chats et journaux adaptés à ta commu.",
    "p3": "Né d'années d'événements au sein de la commu Google Developer Groups, dans la lignée de Last Mile Hero.",
    "credits": "Un projet de {author}, lead GDG.",
    "find": "Trouve un GDG près de chez toi",
    "sources": "Sources"
  }
};
